### ISSUE TITLE
Weird file entries

### ISSUE THREAD

**Issue by Qubits01** [kapitainsky/RcloneBrowser#100]
Hi,

I use Win10 latest, rclone 1.51, rclonebrowser 1.8.0
edit: picture shows rclone 1.50.2. I experimented if downgrading rclone would solve the issue. it did not.
When I list the root of my encrypted gdrive with rclonebrowser, I get this output
![rcb](https://user-images.githubusercontent.com/39989491/78467742-a3589c00-774a-11ea-8e9a-2bdb627e2d60.png)
Of course these files are not really there. When I use my win7 machine these are not displayed.
They also don't show up when I use rclone lsf.
Interestingly, I don't have this problem with another crypted rclone drive using the same win10 machine...

What might be the cause?

**Comment by kapitainsky** [comment]
I have never seen anything like this myself... it is a bit mystery as rclone browser uses rclone lsl and lsd output to show remote content.

could you try latest beta from here? #93 - link in the first post. then you can try to run cryptcheck to check remote integrity.

**Comment by kapitainsky** [comment]
Other thing you mentioned is that it works on some instance of Windows 7 - could you please copy rclone.con from there and try it on Windows 10? It is usually located in %HOME&\.config\rclone\rclone.conf.

And my questions:
1. - Are these weird files only thing you see? Or there are there in addition to your regular content?
2. - Are there in root folder or some specific location?
3. - does "rclone lsl mcrypt:" and "rclone lsd mcrypt:" display right content?

**Comment by Qubits01** [comment]
Hi,

thank you very much for the response and I have to apologize because I have not investigated by myself better before posting here.

Turns out these entries do not show up using rclone up to 1.49.5.
starting from rclone 1.50.0 they do show up when I use rclone by itself, not rclonebrowser.

So it's definitely not an issue with your program and the thread can be closed.

**Comment by kapitainsky** [comment]
I would suggest you post this issue on rclone issues https://github.com/rclone/rclone/issues
or on rclone forum https://forum.rclone.org/

fixing it will benefit everyone.
