### ISSUE TITLE
Rclone Browser UI password protection

### ISSUE THREAD

**Issue by guys101** [kapitainsky/RcloneBrowser#101]
Is it possible to implement some kind of password lock for Rclone browser interface? or simply right click on a remote and lock it with a password?

Say I put portable Rclone browser on a usb and someone stole it, they can't access to my remotes without the password to open Rclone browser interface.
Another example (in my case), I want to use rclone browser to mount a media remote(read-only ofc) in my living room so my friends/guests or my brother friends/guests could watch movie but I don't want them to mess with the rclone browser (when i'm not there).

**Comment by kapitainsky** [comment]
Everything is possible but why to try to reinvent a wheel? All your requirements can be easily achieved utilising OS capabilities. I could try to implement some imperfect password protection but it can't be well done compared to already existing solutions (which are constantly improved, challenged and worked on by many people). Back to your requirements:

1. USB stick. You can use some sort of disk encryption - you have not mentioned OS you are using but there are cross platform solutions like [veracrypt](https://www.veracrypt.fr/en/Home.html). And I am sure your OS has some native ways to encrypt external drive as well.

Other option is to [password](https://rclone.org/docs/#configuration-encryption) protect rclone config file (it is fully supported by Rclone Browser - it will either ask you for password or use password provide by rclone parameters). There are few options here including introduced in the latest rclone --password-command option which let you use password manager stores like [pass](https://www.passwordstore.org/).

2. If you want to mount remotes and prevent other users from messing with your configuration use --allow-other option when mounting and run RB and rclone as different user. It will become easier with the next release where mounts can be auto mounted on RB start.

I don't feel that I could provide fully secure and reliable "password protection". And given that it can be done without it I prefer to spend time on more useful features. Hope it clarifies my point.

**Comment by guys101** [comment]
Thank you for the reply, I will wait for the next release for my living room media mount. As for the usb, encrypt the configuration file was what I looking for and may be try to not losing the usb.

**Comment by guys101** [comment]
btw is there a discord channel for rclone? I feel like my noob's quesiton would fit there better than creating a new issue.

**Comment by kapitainsky** [comment]
There are no stupid questions:) only stupid answer sometimes:)

https://forum.rclone.org/ is good place to discuss rclone
