### ISSUE TITLE
I want RcloneBrowser windows portable

### ISSUE THREAD

**Issue by huanx9** [kapitainsky/RcloneBrowser#102]
tks

**Comment by kapitainsky** [comment]
??? Could you please be more specific?

**Comment by huanx9** [comment]
wow!!   my English is bad   , 

I don't like  *.exe   ,I hope get  *.7z   Do you understand my means ?  thank you !!

**Comment by huanx9** [comment]
releases > RcloneBrowser for windows .7z

**Comment by kapitainsky** [comment]
You can install it copy files somewhere else and that uninstall.

Or if you for whatever reason don't like running installer use https://constexpr.org/innoextract/  to extract files from Windows exe installer.

I have no plans to release other formats.
