### ISSUE TITLE
installation was not successful - mac

### ISSUE THREAD

**Issue by danieleMarenco** [kapitainsky/RcloneBrowser#103]
if I try to configure
does not open the specific page for location .rclone.conf

<img width="970" alt="Schermata 2020-04-10 alle 23 35 07" src="https://user-images.githubusercontent.com/35263803/79024832-65ada600-7b84-11ea-8571-1c4880526494.png">

**Comment by kapitainsky** [comment]
it should open terminal - it is equivalent to running in terminal `rclone config`

**Comment by kapitainsky** [comment]
<img width="990" alt="Screenshot 2020-04-10 at 22 42 44" src="https://user-images.githubusercontent.com/15635386/79025096-c0430400-7b7c-11ea-96c8-9c5a9a0f01e3.png">

**Comment by danieleMarenco** [comment]
yes but i've an basic installation of rclone 
~/.config/rclone 
-rw-r--r--@ 1 dmarenco  staff   232B 25 Mar 17:00 rclone.conf

**Comment by kapitainsky** [comment]
rclone browser is not looking for it unless you explicitly specify it in preferences. Your rclone.conf localtion is default one so it should be picked up without any issues.

Can you run `rclone config` directly from terminal?

**Comment by danieleMarenco** [comment]
<img width="282" alt="Schermata 2020-04-10 alle 23 51 19" src="https://user-images.githubusercontent.com/35263803/79025478-2e3ff900-7b86-11ea-9426-07307476616a.png">

**Comment by kapitainsky** [comment]
ok so issue is with invoking command in terminal... what version of macOS you are on?

**Comment by danieleMarenco** [comment]
Catalina 10.15.4

**Comment by kapitainsky** [comment]
ok - the same here - it must be something specific with you account setup. I am trying to figure out what it might be

**Comment by kapitainsky** [comment]
what shell you are using? sh? bash? or something else?

**Comment by danieleMarenco** [comment]
sh

i don't know if rcloneBrowser saves tmps etc.
maybe delete them?

**Comment by kapitainsky** [comment]
or actually... looking at your initial screenshot... RcloneBrowser does not know where rclone is... because otherwise it would show it's version:

<img width="885" alt="Screenshot 2020-04-10 at 23 14 15" src="https://user-images.githubusercontent.com/15635386/79026532-17e36e80-7b81-11ea-834e-dd42984a2104.png">

just open preferences and point it to rclone executable

**Comment by danieleMarenco** [comment]
yes I agree,
but I click to click Confg ... on rcloneBrowser 
open in automaticaly this terminal :
<img width="704" alt="Schermata 2020-04-11 alle 00 17 20" src="https://user-images.githubusercontent.com/35263803/79026709-f89d0f00-7b89-11ea-8cd2-9e789681d952.png">

**Comment by kapitainsky** [comment]
ok - it is a bit misleading. "Config" button open rclone config.

To open preferences:

<img width="912" alt="Screenshot 2020-04-10 at 23 21 11" src="https://user-images.githubusercontent.com/15635386/79026868-16ff0c80-7b82-11ea-8c6b-3b7a8f4e6b7f.png">

**Comment by kapitainsky** [comment]
Also if you want you can try the latest release (BETA). I will release it in few days:

https://1drv.ms/u/s!Aq335pidOrBV4IJJ-XhPhrvqr9KEBw

Any comments welcomed

**Comment by kapitainsky** [comment]
you gave me idea that I should disable config button if rclone is not configured - or display some info what to do. On "to do" list now

**Comment by danieleMarenco** [comment]
ok thank you, good 

and for location rclone?
<img width="741" alt="Schermata 2020-04-11 alle 00 26 19" src="https://user-images.githubusercontent.com/35263803/79027203-a3fa9380-7b8b-11ea-97d9-6d800fd5cd9b.png">

**Comment by kapitainsky** [comment]
rclone location is only preference required (unless you want to use rclone.conf in other than default location - but your rclone uses deafult).

So just point `rclone location` to rclone executable

**Comment by kapitainsky** [comment]
on first run after installation it should ask you where rclone is... but if you press escape or ignore it I think it does not ask more.

**Comment by kapitainsky** [comment]
When I have some time I will try to improve this. Should be easy to warn user what is missing. Indeed as it is now I can see that it might lead to some confusion what is wrong.

**Comment by danieleMarenco** [comment]
now works 
Thanks a lot for the collaboration ;)

**Comment by kapitainsky** [comment]
Cool! try the latest version - tones of new stuff and improvements
