### ISSUE TITLE
Request: See command of task.

### ISSUE THREAD

**Issue by AplhaSlayer1964** [kapitainsky/RcloneBrowser#105]
I know the whole point of the browser is to not have to deal with the command line but would it be possible to add a button or tab on a task that shows the final command that is sent to rclone? Might help with troubleshooting etc.

**Comment by kapitainsky** [comment]
This is actually very useful and I use it a lot - as it is already implemented. 

Running jobs have “copy rclone command to clipboard” button. Next to cancel one.

**Comment by AplhaSlayer1964** [comment]
woops didn't realize it was already implemented! Thanks for letting me know.

**Comment by guss77** [comment]
It still would be nice to have that feature added to the task list - so I don't have to run the job to know how the command line should look.

Use case: I love the UI to configure tasks. Often I want to have tasks recurring automatically in a cron-job or sth.

My current workaround is:
- Create task in RcloneBrowser
- Dry run the task
- Copy the task command line from the job
- Use the command line in a job scheduler.
- Optional: delete the task configuration

Another alternative is to have a command line to run tasks, such as `rclone-browser run-task my-task-name`, which may even work without a UI (so I can actually run it from a cron-job). This would be super useful as I could maintain my rclone scripts in a nice GUI and edit them as needed.

**Comment by kapitainsky** [comment]
I have added it already in the upcoming release.

It will also have scheduler + option to start RB minimized to system tray... so you will be able to achieve everything without any extra tools.

Would you like to test beta version? If yes let me know what OS you are on and I will do beta release.

**Comment by guss77** [comment]
@kapitainsky - I would love to test a beta version. I'm running Ubuntu 20.04, and I can also build from git - I've tried rebuilding `master` and `kptsky_experimenting` but didn't see any changes from the Ubuntu 1.8.0 release.

**Comment by kapitainsky** [comment]
https://1drv.ms/u/s!Aq335pidOrBV4IJKtjw8gMzslz_aHQ

contains queueing and scheduler

**Comment by kapitainsky** [comment]
if you would like newer version compile from kptsky_testing

In general testing branch contains working code, experimenting is my experiments:) - i might not compile or even break things - not recommended. When I am happy that code is working I merge it to testing - then when really happy to main and do release.

**Comment by guss77** [comment]
I checked the beta version - looks very good.
Notes:
1. I didn't see an option to copy the rclone command line for the task (not the job).
2. The new queue and scheduler look like very useful features that a lot of users would enjoy - though for myself I would have liked to be able to schedule jobs without relying on a GUI application running: I would very much like to be able to execute rclone-browser tasks from the command line without a UI, and handle the scheduling myself using facilities already integrated into the operating system, such as SystemD timers.

**Comment by kapitainsky** [comment]
> 
>     1. I didn't see an option to copy the rclone command line for the task (not the job).
Still in experimenting. I thought that it will be trivial but turned to require changes in few classes - will be ready in few days - will send you a link with updated beta when I move it to testing.


>     2. The new queue and scheduler look like very useful features that a lot of users would enjoy - though for myself I would have liked to be able to schedule jobs without relying on a GUI application running: I would very much like to be able to execute rclone-browser tasks from the command line without a UI, and handle the scheduling myself using facilities already integrated into the operating system, such as SystemD timers.

Fully understand - everybody uses it in different way. I have some thoughts about cmd API in the future - but not soon. Now want to finish few more things - especially working on multiselection in remotes - so you could down/upload multiple items in one go. I have limited time and have to prioritise:)
