### ISSUE TITLE
i need auto mount after start the application . enhancement

### ISSUE THREAD

**Issue by verneSil** [kapitainsky/RcloneBrowser#106]
##this is  realy a wonderful and helpful project .
but i just need a feature
i hope it can auto mount to some dir after start the application .thank you.

**Comment by kapitainsky** [comment]
Yes it can in the upcoming release and also start minimized to systray. So wait few more days. I am finalising it. It takes longer than expected as there is plenty of new things I want to make sure work well before releasing it.

**Comment by kapitainsky** [comment]
you can try beta from here #93  - link is in the first post

**Comment by verneSil** [comment]
> you can try beta from here #93 - link is in the first post

twow. i will try .thank you  again.
