### ISSUE TITLE
RC PASSWORD is not correct

### ISSUE THREAD

**Issue by alado70839** [kapitainsky/RcloneBrowser#113]
When the RC generate random username and password, it always shows XXXX for the password, I copy and paste the password, it's not correct. Where I can setup the username and password??

**Comment by kapitainsky** [comment]
Could you please provide more details?

what OS?
shows where?

**Comment by alado70839** [comment]
Hello,

I'm using macOS 10.14
![image](https://user-images.githubusercontent.com/57855263/80688011-be29f080-8afd-11ea-9cbb-b7dad07cb8e9.png)

**Comment by kapitainsky** [comment]
I assume you are using the latest beta version.

When you mount new drive you have an option to invoke custom script and run mount with RC interface enabled.

After successful mount RB will invoke defined custom script passing all required parameters.

/path/customScript.sh arg1 arg2 arg3 arg4 arg5

where:

arg1 - rclone location
arg2 - RC port used
arg3 - RC user name
arg4 - RC password
arg5 - mount point

have a look at #93 where I give some example how to use it.

You can't define username/password - there are always random. You can have a look what they are when you copy rclone command (copy to clipboard icon on your screenshot - top right corner)

**Comment by alado70839** [comment]
Thank you, I'm using the latest beta, and it's very good! All I need it to refresh the mount manually after uploading the new data . I checked the #93, but I don't know how to convert the windows script to macos script. Attached my mount setting

![image](https://user-images.githubusercontent.com/57855263/80689067-583e6880-8aff-11ea-85c5-a669563a44db.png)

**Comment by alado70839** [comment]
Thank you. I went back and copy to the clipboard. Now I can see the password.

**Comment by kapitainsky** [comment]
I will provide some working example for macOS in final release, in the meantime try this:

```
#!/bin/bash


echo $1
echo $2
echo $3
echo $4
echo $5

echo off

sleep 10

echo.
echo Warming up cache...
echo This may take a few minutes to complete
echo You can use the cloud-drive normally while this runs
echo.

$1 rc vfs/refresh -v recursive=true --rc-addr localhost:$2 --rc-user $3 --rc-pass $4

if [ $? -eq 0 ]
then
  echo Cache warmup for $5 OK!
else
  echo Something went wrong during precaching.
fi
```

When run with script you can also see script output in jobs:

<img width="1552" alt="Screenshot 2020-04-30 at 09 35 13" src="https://user-images.githubusercontent.com/15635386/80689960-01686d00-8ac6-11ea-8097-1e9236dd5594.png">

**Comment by kapitainsky** [comment]
The line `sleep 10` is a bit crude solution - next step requires mount to be already mounted. Waiting for 10s should work for testing. In final version it should probably run `df` and wait for filesystem to be mounted.

**Comment by alado70839** [comment]
I tried to copy and paste your script and save as .sh file. But it can't not be run, did I do something wrong?
![image](https://user-images.githubusercontent.com/57855263/80690516-7b6a1780-8b01-11ea-9d22-041d2cb65b36.png)

**Comment by kapitainsky** [comment]
I am not expert on mount options but your example as I understand will use 512G of cache - but in memory as you don't specify disk location. If you have enough memory it is ok, otherwise put it on disk maybe"

`--cache-dir "/pathToCache/CacheFolder"`

**Comment by kapitainsky** [comment]
sh file is script so you have to make it executable

**Comment by alado70839** [comment]
OK, I will try it and provide the feedback. I didn't specify the location and it used default path, I will try to change it if necessary, thank you.

**Comment by kapitainsky** [comment]
Any feedback is welcomed.

**Comment by alado70839** [comment]
Thank you, it's working now. I will be closing this issue task. One thing not related is the stream performance. I'm using the 100M network, but the mount is steam slow when using the emby on kodi when playing videos. I check rclone forum, it may be the macos FUSE issue, but I'm not sure. 

![image](https://user-images.githubusercontent.com/57855263/80691833-5e364880-8b03-11ea-96f7-c911ccc267ee.png)

**Comment by kapitainsky** [comment]
> Thank you, it's working now. I will be closing this issue task. One thing not related is the stream performance. I'm using the 100M network, but the mount is steam slow when using the emby on kodi when playing videos. I check rclone forum, it may be the macos FUSE issue, but I'm not sure.
> 

Yes rclone forum is right place as it has nothing to do with RB.  FYI at the moment with 30MBits Cx I have no issues streaming even HD videos - I use RB and vlc. 

This can be related to many things including your remote performance.

**Comment by alado70839** [comment]
Now the mount is not showing any content only folders after the script ran, am I supposed to wait a long time to get the files
![image](https://user-images.githubusercontent.com/57855263/80720219-3230bc80-8b2f-11ea-9c4f-a6d3f3b43023.png)

**Comment by kapitainsky** [comment]
Check your mount options. Rclone Browser let you run in easy way mount command, then if you want post mount sctipt. But what your options do is out of its scope.

You have to troubleshoot how you mount. Try without script - if still the same try maybe without any extra options.

Also you can try run the same mount from command line.

**Comment by alado70839** [comment]
It could be 10s is too short for the mounting. I removed the script and it goes back to normal.

**Comment by kapitainsky** [comment]
You can get maybe idea from here:

https://forum.rclone.org/t/a-short-primer-on-pre-caching-or-pre-listing-technique/13171

**Comment by alado70839** [comment]
Thank you, I will try out.

**Comment by kapitainsky** [comment]
let me know if you make it work - might be useful to include as an example for others

**Comment by alado70839** [comment]
It's bit weird that I had 1 mount works but another failed by using the exactly the same mount setting and the same script. The only difference between these two is the one worked is the shared team drive by others, I only have the read permission.

**Comment by kapitainsky** [comment]
is it Google drive?

if yes add --drive-shared-with-me option

**Comment by alado70839** [comment]
Yes, it's google drive. But the one failing is my own drive, not the team drive. When I removed the script, I can see getting the list take more time to come out since I have many folders.

**Comment by alado70839** [comment]
after testing several combination, removing recursive=true works, not sure why. But the mounting folder get updated.
