### ISSUE TITLE
Automount at start?

### ISSUE THREAD

**Issue by bigalgeorge** [kapitainsky/RcloneBrowser#114]
Hi am I missing something? I set up local directories for gdrive onedrive and so on; each mount as a separate folder.
I would expect that when rclonebrowser is started, that these drives which have mounts allocated would already be either waiting to be mounted in nemo, or already mounted, but what Im getting is I have to click on each remote in the browser, mount it and redefine the mount point.

Thanks, Al.

**Comment by Darthagnon** [comment]
It should automount drives if you save them as tasks. does for me, tested with mega.nz - I save the mount as a task, enable "Run saved task every time RCloneBrowser starts", and boom. it works (v1.9.8.0 beta)

**Comment by bigalgeorge** [comment]
Gr8 idea. Gave me inspiration to check it out and another way is to write a script eg mount.sh
1..make a directory for mounts. #mkdir /home/alistair/OnlineDrives/
2..write the script similar to following (mine is in above directory named mount.sh:
#!/bin/bash
/usr/bin/rclone mount Mega: /home/alistair/OnlineDrives/Mega &
/usr/bin/rclone mount Onedrive: /home/alistair/OnlineDrives/Onedrive &
/usr/bin/rclone mount GDrive_AG: /home/alistair/OnlineDrives/GDrive_AG &
/usr/bin/rclone mount GDrive_KKCC: /home/alistair/OnlineDrives/GDrive_KKCC &

save and make file executable. Notice, I have several shares.
#crontab -e
#@reboot sh /home/alistair/OnlineDrives/mount.sh
(above mounts everything listed on reboot)

**Comment by Darthagnon** [comment]
Looks like that works good! That's the way that rClone works :D You're a better programmer than I am 

NB. it looks like you're bypassing the need for a GUI like RCloneBrowser, and just using the rclone backend CLI... RCloneBrowser, I believe, is supposed to make it easier for people to do exactly what you did, but without CLI.

Are you on the latest beta of RCloneBrowser, out of curiosity (or maybe the beta was only for windows)? as it should make it possible to do what you did via GUI.

**Comment by bigalgeorge** [comment]
Ive started to use the rclonetray, as this project is closed. But using my previous method, you dont need anything else really. However, I have been having a really hard time getting rclone to work with cpanel web disk; spent a day on it with nothing positive.

**Comment by bigalgeorge** [comment]
Finally I have managed to get rclone to work with web disk.
These are the tips:
1..Select type Webdav
2..url in format Value "url" = "https://webdisk.myhost.com"
3..Value "user" = "username@myhost.com"
4..MOST IMPORTANT!! do not try to copy/paste password; the interface shows no asterisks on entry, and confusion is easy here. Note also, your password is encrypted by rclone, and it will not display same as you typed it in on later edit.

Good luck!
