### ISSUE TITLE
Rclone Sync

### ISSUE THREAD

**Issue by NQK** [kapitainsky/RcloneBrowser#131]
Could you implement two sync/copy/copyto features?

edit: Found it.

**Comment by sakshatshinde** [comment]
Could you point me to the resource you found to copy/copyto feature? @NQK

**Comment by sakshatshinde** [comment]
Ok I found a way as well. Anyone looking on how to do this:

Just use the **download** option and set the path. It doesn't have to be your own computer it can be a shared drive or your drive as well.
