### ISSUE TITLE
The shortcuts saved in my drive don't show up

### ISSUE THREAD

**Issue by shelra** [kapitainsky/RcloneBrowser#147]
I installed this on pop directly from apt, didn't know there was another rclonebrowser. so issue is that I have shortcuts of files which are in team drives which I have access to, saving the shortcuts of files to my drive eases the process as I don't have to configure a team drive and could access files via shortcut directly from my drive remote. This was possible in another rclone browser so I dont see why it cant be here

**Comment by shelra** [comment]
seems pop os installed older version, never thought that would be root.
**check version of rclone always

**Comment by kapitainsky** [comment]
Thank you for letting me know! One issue less to investigate.

**Comment by DIGITALCRIMINAL** [comment]
Ahh yea, forgot to update rclone, was wondering why I couldn't see the shortcut in the team folder 👍
