### ISSUE TITLE
how can i set cache dir?

### ISSUE THREAD

**Issue by skyzombie89** [kapitainsky/RcloneBrowser#149]
Where is the default location for cache?

can i change it? 

mount G Drive:/ F: –allow-other –cache-dir=D:\Rclone_Cache --allow-other --fast-list --drive-skip-gdocs --poll-interval=1m --buffer-size=32M --vfs-read-chunk-size=32M --vfs-read-chunk-size-limit 2048M --vfs-cache-mode=full --vfs-cache-max-size 200G --vfs-cache-max-age 24h --dir-cache-time=1000h --log-level INFO

i usually use setting like upside. but in preferences, there are so many option blank. 

please tell me which blank should i put those setting

**Comment by kapitainsky** [comment]
yes you can and you already do it " –cache-dir=D:\Rclone_Cache". You can change it your preferred location

**Comment by skyzombie89** [comment]
> yes you can and you already do it " –cache-dir=D:\Rclone_Cache". You can change it your preferred location

 where should i put those option in Rclone browser?

file/preferranece/ general -----> there are so many blank

mount option? defaul up/download option? defailt rclone option? where?

**Comment by kapitainsky** [comment]
mount option
