### ISSUE TITLE
Default download directory and save the last used destination folder

### ISSUE THREAD

**Issue by danoe** [kapitainsky/RcloneBrowser#15]
Right now when I click on download, the destination folder is always empty, but if i click on the browse button it shows me the folder i opened last.

It would be great if the last used folder could be kept for the next download.

In general it would also be nice to have a global default download directory that is used on startup of rclone browser.

**Comment by kapitainsky** [comment]
Agree. It makes sense. I will try to add this to the next release. Should not be too difficult. 

Rgds

Dariusz

**Comment by kapitainsky** [comment]
It has been added. Either you wait  for the next release or compile from my test branch (kptysky_testing). I will do next release when rlcone releases v1.50 so I can fix unmounting in windows.

**Comment by danoe** [comment]
Thanks so much, I'll probably wait for the v1.50 then.

**Comment by kapitainsky** [comment]
Fixed in just released [1.6.0](https://github.com/kapitainsky/RcloneBrowser/releases/tag/1.6.0)
