### ISSUE TITLE
Does Rclone Browser keep a file where the Tasks I have created are saved?

### ISSUE THREAD

**Issue by rubensgpl** [kapitainsky/RcloneBrowser#155]
Something like a log file.

**Comment by rapenne-s** [comment]
This [function](https://github.com/kapitainsky/RcloneBrowser/blob/master/src/list_of_job_options.cpp#L124) saves your jobs.

On Unix it saves it under `$HOME/.local/share/rclone-browser/rclone-browser/tasks.bin`.

**Comment by kapitainsky** [comment]
check here -  https://github.com/kapitainsky/RcloneBrowser#portable-vs-standard-mode for all files locations in all supported operating systems
