### ISSUE TITLE
Preferences location when building from source

### ISSUE THREAD

**Issue by kennyparsons** [kapitainsky/RcloneBrowser#165]
Where is the preferences file if I've built this from source? It's not in either of these locations: 
 - `~/.config`
 - `~/.local`

**Comment by kapitainsky** [comment]
https://github.com/kapitainsky/RcloneBrowser#portable-vs-standard-mode

**Comment by kennyparsons** [comment]
@kapitainsky Rclone Browser is not storing its preferences there. After running rclone browser, setting some preferences, closing, and relaunching, all preferences are back to stock. Does rcbrowser automatically make the files/folders?

**Comment by kapitainsky** [comment]
yes - all folders and files should be created automatically. What OS you are on?

**Comment by kennyparsons** [comment]
debian 10

**Comment by kapitainsky** [comment]
I wonder what it might be - I do not manage these files by hand but rely on Qt to do the job. Maybe Qt version plays some role here? I will try on Debian 10 tomorrow and see.

**Comment by kapitainsky** [comment]
can you try AppImage version from releases? It should tell us if something is broken in the app or rather it is something specific to your build.

**Comment by kennyparsons** [comment]
I should clarify, I'm running this in a debian 10 container with an X server. It's running as user 1000 (uid/guid) and the home directory is also owned by that user. So running an app image is much harder than the binary.

**Comment by kennyparsons** [comment]
Is there a verbose mode to rclone-browser?

**Comment by kapitainsky** [comment]
not verbose mode at the moment yet.

My wild guess would be that it is related to your environment and Qt configuration files saving fallback mechanism - 

https://doc.qt.io/qt-5/qsettings.html#fallback-mechanism

See "Platform-Specific Notes" - maybe your setup has some mentioned system variables set to locations where you have no write permissions?

Maybe your $HOME variable points somewhere where app can't write?

**Comment by kennyparsons** [comment]
@kapitainsky QT isn't using the `$HOME` directory. It's using `$XDG_CONFIG_HOME`. Just found the directory and the associated config file. Not sure if this is QT's default when the env is set or not, but it might be helpful to note this in the docs if anyone else might have the same issue.

**Comment by kapitainsky** [comment]
Thank you for letting me know. Always good to understand.
