### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by caspertone2003** [kapitainsky/RcloneBrowser#18]
What needs to be installed?
![image](https://user-images.githubusercontent.com/4682903/66231301-7caba100-e6e6-11e9-828a-cfa0d5ef8906.png)
Seems Appveyor upgraded their Visual Studio version...
Could you include the dll in the release?

**Comment by caspertone2003** [comment]
64 bits vcruntime - https://aka.ms/vs/16/release/vc_redist.x64.exe
32 bits vcruntime - https://aka.ms/vs/16/release/vc_redist.x86.exe

Looks that just including vcruntime140_1.dll in RCloneBrowser directory is enough

CT

**Comment by kapitainsky** [comment]
Sorry I do not use Appveyor.
Happy to add whatever is needed for those who do. Could you please point me what has to be done?

**Comment by caspertone2003** [comment]
Just including with the rclonebrowser.exe in the same folter the file vcruntime140_1.dll
You can get the file installing any of the following:
64 bits vcruntime - https://aka.ms/vs/16/release/vc_redist.x64.exe
32 bits vcruntime - https://aka.ms/vs/16/release/vc_redist.x86.exe

If you do not use Appveyor seems that you use a brand new version of VB.

**Comment by kapitainsky** [comment]
I use Visual Studio 2019

**Comment by kapitainsky** [comment]
Sorry for stupid question but I am not using Windows - so have not much clue about this environment. Do you mean that without this DLL vcruntime140_1.dll  you cant run Rclone Browser? I tested my release on couple of virtual machines I use and it always worked. And I never installed it - maybe some other software did it? and I was lucky?

**Comment by kapitainsky** [comment]
OK I managed to replicate this issue. I got it now. It will be fixed. This is easy one. I guess many people have this dll installed because of other apps installing runtime for VC. But unlucky ones see error. I will include it in the next release. Thank you for letting me know.

**Comment by kapitainsky** [comment]
fixed. latest release will have this dll in few minutes and I will keep in for future releases

**Comment by caspertone2003** [comment]
I had installed the visual studio runtime 2017. Not many runtimes in my VMs ;-)
But this dll is new of 2019, so I got this.
Thanks again for refloating RcloneBrowser!
CT
