### ISSUE TITLE
video player seeking problem

### ISSUE THREAD

**Issue by pakosaan** [kapitainsky/RcloneBrowser#184]
Cannot seek to specific timestamp of the video playing in either of vlc or mpv players. Seeking is only possible to the precached section. I cannot click to the uncached section

**Comment by kapitainsky** [comment]
possible. It is rclone behaviour not rclone browser. This is where you should raise this issue.

In my opinion streaming rclone functionality is not something you should count on. This is not what is the purpose of this tool. It is rather for some "testing/emergency" situations only.

**Comment by pakosaan** [comment]
if i stream using the rclone serve dlna from the terminal . Then i can seek to any part of the video either cached or not. But its not the case for rclone-browser stream.
I only use the rclone-browser because it let me stream through the mpv player as mpv doesnt support upnp dlna. But i cant skip parts when streamed from the rclone browser.

**Comment by kapitainsky** [comment]
what rclone command are you using from terminal?

**Comment by pakosaan** [comment]
I normally use  "rclone serve dlna  remote:" to stream the video. But only the upnp supported player can open the  videos like vlc. mpv doesnt support the feature . But rclone brower let me stream with the both vlc and the mpv player but i cannot seek forward to the video util its cached which is annyoing everytime when i want to continue watching video which i left midway. Can u gime me ome suggestion .Thanks for the reply.
