### ISSUE TITLE
Time Jump in the stream video

### ISSUE THREAD

**Issue by pakosaan** [kapitainsky/RcloneBrowser#187]
video streamed from the rclone-browser  wont allow the user to jump between the specific time unless its cached. So wil it be fixed in the next update?

**Comment by pakosaan** [comment]
Which streaming does rclone-browser  inside. rclone use upnp serve dlna for streaming. and it desnt have the problem of seeking forward in time. but when streaming with rclone browser i cannot  seek forward until it is cached and i have to wait forever. It is the only problem i am facing. Others i dont have any issue. Hope you can help me with this. Thank You.

**Comment by erickyun** [comment]
> Which streaming does rclone-browser inside. rclone use upnp serve dlna for streaming. and it desnt have the problem of seeking forward in time. but when streaming with rclone browser i cannot seek forward until it is cached and i have to wait forever. It is the only problem i am facing. Others i dont have any issue. Hope you can help me with this. Thank You.

I found a workaround 
`rclone serve http encrypt-team: --config=D:\Anime\zTools\Rclone\rclone-v1.57.0-windows-amd64\rclone\rclone.conf --cache-dir=D:\Anime\zTools\Rclone\rclone-v1.57.0-windows-amd64\Cache\`
if you go to `localhost:8080` in your browser and copy paste video link to mpv you can now seek and the player will download entire video. 👍 

I'm noob myself found out rclone 2 days ago and was facing the same problem as you so I decide to share my intel hope this will help you :)

**Comment by kapitainsky** [comment]
Thank you for good tip.
