### ISSUE TITLE
Config in the rclone-browser.

### ISSUE THREAD

**Issue by pakosaan** [kapitainsky/RcloneBrowser#189]
When i click in the  config in the rclone-browser nothing happens.

**Comment by kapitainsky** [comment]
What OS you are on?

**Comment by pakosaan** [comment]
I am using Arch linux

**Comment by RichardBronosky** [comment]
BUMP!

- Version:
    - `rclone-browser-1.8.0-a0b66c6-linux-x86_64_19b798f585da517ed5d4e87d726c604c.AppImage`
-  `uname -a`
    - `Linux brunoarch 6.8.5-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 01:47:18 +0000 x86_64 GNU/Linux`
- `env | grep -E 'TERM|QT_QPA_PLATFORM'`
    - `COLORTERM=truecolor`
    - `QT_QPA_PLATFORM=xcb`
    - `TERMINAL=alacritty`
    - `TERM_PROGRAM=tmux`
    - `TERM_PROGRAM_VERSION=next-3.4`
    - `TERM=tmux-256color`
