### ISSUE TITLE
QUESTION: does the 'refresh' button do anything special?

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kapitainsky/RcloneBrowser#191]
Sorry to trouble you, but I have a question.

I have some shell scripts that use rclone. Those scripts seem to say that a remote item (file) exists when in fact I have deleted it. Yet - by coincidence? - after I click 'refresh' in RcloneBrowser then my scripts register the deletion. Hence my question. That is: is your 'refresh' command sending some special command to my 'remote'? (My remote is on the 'b2' platform.)

**Comment by kapitainsky** [comment]
Nope it does not send any specific command - just re-reads the remote content. From your description it looks that rclone itself caches content - so what you see is not remote content but cached one. Now both your script and browser I assume use the same rclone instance - so if you re-read remote in one, it is reflected in the other.

**Comment by LinuxOnTheDesktop** [comment]
Thank you for the help.

Hmm. I imagine that the following is the case. My script runs one instance of the Rclone binary that I have on my system and RcloneBrowser reads another. I could try to check. (Actually, I did try to check. But I was hindered by an rclone-browser process - which I was not expecting to see at all, because I had closed RcloneBrowser - possessing 'zombie' status.)

**Comment by LinuxOnTheDesktop** [comment]
Closing, because you (@kapitainsky) explained how the 'refresh' button works and because the explanation for a delay in rcloneBrowser registering a deletion is a delay on the part of my cloud provider (that provider being 'Backblaze B2').
