### ISSUE TITLE
Potential improvements

### ISSUE THREAD

**Issue by caspertone2003** [kapitainsky/RcloneBrowser#2]
@kapitainsky 
Thanks again to refloating rclonebrowser!

nice to have a nice icon for mega ;-)

You know... users are insatiable.
We just got a new gift (your new fork with issues solved) and we alwsy as for more...

- Cut/past or drag features a la explorer, both files and folders, in windows would be very nice

- Unmount in windows seems to fail. I found I way in CMD with rclone (find pid of rclone mount process spawned and send signit) but this seems not to be working properly.

- If one uses just a pair of remotes GUI is ok, but as soon as you might have an important number of them the GUI becomes clumsy.
Would be nice in the GUI:
a) to be able to select more that a config file (so one can have accounts grouped by purpose or cloud or whatever)
b) to be able to have more that one remotes tab
c) to be able to assign an icon or image to each remote by colour
d) to hide remotes; for example, if one is using a crypted remote, to hide the base remote...

Thanks!

**Comment by kapitainsky** [comment]
I am happy that you found it useful. 

My only objective at the moment was to fix small annoying bugs and re-release it for all OS platforms. Unfortunately I don't plan to do any development on new features. As it is now it meets my needs. But who knows maybe one day when I have more time I will add some bits.

In regards to your list please note that drag and drop works for uploads (I tested on all platforms). Issue with mount/unmount is not related to browser but to [rclone](https://github.com/rclone/rclone) itself (or for Windows platform to [WinFsp](https://github.com/billziss-gh/winfsp) FUSE emulation layer) - I suggest you seek help on their forums. I do not use Windows myself so don't have much experience here.

**Comment by caspertone2003** [comment]
Thanks!
