### ISSUE TITLE
Issue with seeking while streaming (WIndows)

### ISSUE THREAD

**Issue by jayloofah** [kapitainsky/RcloneBrowser#20]
I've tried out a few media players on the Stream function but none of them seem to be able to seek. If I mount the remote and stream that way seeking is possible, but there is [another current issue](https://github.com/kapitainsky/RcloneBrowser/issues/13) with unmounting on Windows that is already open.

I guess there might be some configuration issues with the media player, but it lead me to think that it might be worthwhile to have some advanced config options (additional flags) the stream and mounting functions, just in case there are issues.

Thank you again for taking up this project which I feel is severely needed for rclone (their current gui is way behind).

**Comment by danoe** [comment]
Which remote are you using? Google Drive? Are you using your own API credentials? 
If you use the default ones you might run into the rate limit, see here: https://forum.rclone.org/t/seeking-in-a-gdrive-mount-hangs/8615

**Comment by jayloofah** [comment]
Yes, Drive. And I am not.

I see, so I should add API creds to all of the remotes I'm using?

**Comment by kapitainsky** [comment]
I believe seeking always will be problematic due to nature of cloud storage. There are usually object storage systems and do not offer downloading specific parts of files.

**Comment by jayloofah** [comment]
Okay, well I just thought I would mention the bug since the streaming behavior works normally if the remote is mounted and the media file is played. Thank you.

**Comment by kapitainsky** [comment]
Streaming invokes rclone reading a remote file and redirecting stream of data to your configured player. It can't jump forward as all stream has to be read first.

When you mount remote there is another layer (FUSE) which provides buffering. FUSE simulates typical file system and might read file content in advance. When already buffered in file system your player can read whatever part of the file you request.

And in both cases player provides its own buffering

So it is not a bug per se but rather nature of rclone.

**Comment by jayloofah** [comment]
[Like you said...
](https://github.com/mmozeiko/RcloneBrowser/issues/3#issuecomment-276519233)

Ok then, this issue can be closed, thank you.
