### ISSUE TITLE
Donating: two problems

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kapitainsky/RcloneBrowser#216]
Hello! I wanted to donate. I discovered that you were taking donations for 'code signing certificates'. Problem 1: I don't understand the function of money donated for that purpose. Problem 2: I tried to donate nonetheless, using - the only option? - PayPal. I tried both the 'friends and family' and the 'commercial' option, but both times my payment was rejected.

I wanted to donate because I find your software to be pretty good at doing a very useful job (although I believe that, were I more of a terminal wizard, then `rclone mount`, and some ncurses inbuilt-rclone file manager thingy, might serve a similar purpose to your program).

**Comment by LinuxOnTheDesktop** [comment]
On problem 2: I found that I had a SMS from my bank warning of fraud and asking for confirmation of payment. I responded to the SMS by approving the payment. Please advise whether you have received the payment.

**Comment by moklinowski** [comment]
I made a donation 2 years ago by Paypal and no worry at all.

**Comment by LinuxOnTheDesktop** [comment]
The problem turns out to have been at my end. Apologies! Donation made.
