### ISSUE TITLE
Store tasks in same folder as rclonebrowser.exe

### ISSUE THREAD

**Issue by caspertone2003** [kapitainsky/RcloneBrowser#22]
Seems that tasks in Windows are stored in user / AppData / Local / RcloneBrowser / RcloneBrowser
in a file called tasks.bin

This breaks portability.

Looks that storing in within the same directory of RcloneBrowser or in a subdirectory such as StoredTasks might solve the issue.

Thanks,
CT

**Comment by kapitainsky** [comment]
good point. tasks are not included in portable configuration. At the same time it is not very critical but I will add this for future enhancements list.

**Comment by kapitainsky** [comment]
Fix has been released in 1.7.0. Let me know if it works now.

**Comment by caspertone2003** [comment]
In order to run 1.7.0 I had to install in PC "A", then copy folder to PC "B", as in the last one I have no rights to install programs. RB runs well.
But, at least in the way done, tasks are still stored in
C:\Users\MYUSER\AppData\Local\rclone-browser\rclone-browser

I am not sure if this is solved in the installed version... Why not save it into a subfolder where the rclonebrowser.exe is being run?

Thanks for considering this point!

**Comment by kapitainsky** [comment]
Let me investigate it.  I was sure it is fixed if you run in portable mode (you have to create ini file with the same name as exe)
