### ISSUE TITLE
Feature request - launch hidden in tray

### ISSUE THREAD

**Issue by ivandeex** [kapitainsky/RcloneBrowser#26]
Please add a checkbox that makes RcloneBrowser start hidden in Windows system tray.

**Comment by kapitainsky** [comment]
And what would the purpose of it?

**Comment by ivandeex** [comment]
Let me list here more feature ideas on the road to make RcloneMount a full-featured rclone mount GUI. We can create respective feature request tickets later:
* Drop-down selector for mount disk letter
* Save/restore last used mount disk letter, per remote
* Option to auto-start on user login

Autostart: RB can either write its path in the regisrtry under HKCU/**/CurrentControlSet/**/Run  or create a shortcut under /Users/user/AppData/roaming/Microsoft/Windows/Start  Menu/Startup)

**Comment by ivandeex** [comment]
> And what would the purpose of it?

My use case is RcloneBrowser as a tray wrapper for `rclone mount` auto-loaded upon login.

PS Thank you so much for giving this project a new life.

**Comment by kapitainsky** [comment]
No plans on my side to make Rclone Browser some sort of RcloneMount tool. Main focus in on remotes browsing and files transfer. I treat mount feature as useful addition only. I consider cloud storage mounts to be inherently unreliable hence only useful for poking around and copy in/out few small files.

Maybe you need something like this?:
https://github.com/dimitrov-adrian/RcloneTray

**Comment by ivandeex** [comment]
Got you. Will DIY.
