### ISSUE TITLE
RcloneBrowser 1.6 with Rclone 1.50, on Windows: no remote listed or accessible

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kapitainsky/RcloneBrowser#27]
I've just installed RcloneBrowser 1.6 and Rclone 1.50, on Windows. When I run RcloneBrowser no remotes are listed and the 'config' and 'rerfresh' buttons seem to do nothing. In the RcloneBrowser settings, the paths seem correct.

**Further information**

I don't use rclone on its own on this machine.
I copied the rclone conf file from a Linux computer on which I use rclone (on its own) and rcloneBrowser.
Windows 10 1903

PS: Nice new tray icon on Windows!

**Comment by kapitainsky** [comment]
Go to preferences and point rclone browser to locations of rclone.exe and config.

**Comment by kapitainsky** [comment]
let me know if you still have an issue. we can troubleshoot it

**Comment by LinuxOnTheDesktop** [comment]
Thanks. I did as you suggested - even though the paths were correct already. All that changed was: the slashes in the paths became Linux-style rather than Windows-style; the remotes pane remains and empty and the buttons in that pane still do nothing.

**Comment by kapitainsky** [comment]
does Rclone Browser shows rclone version in main window footer?

can you run rclone from command line? try path_to_your_binary\rclone.exe --version

Seems like for whatever reason your rclone binary does not run so browser can't use it

**Comment by kapitainsky** [comment]
Do you try to run this from some sort of virtual machine? If so move your binary and config out of shared folders. Windows have issues using shared folders for many operations.

**Comment by LinuxOnTheDesktop** [comment]
Thanks.

I am running Rclone Browser on real (not virtualised) Windows.

Rclone version number: I told you the version that I thought I had installed; the window itself shows no number:

![image](https://user-images.githubusercontent.com/47056543/67637791-03aefc00-f8d6-11e9-829e-266621c07086.png)

But - aha! For some reason the rclone binary was set to run as administrator. When I made it run as a normal user, Rclone Browser started working. Ideally, you would build some sort of check for this problem into your program.

**Comment by kapitainsky** [comment]
Great that it works! Yes it would be nice to have all sort of checks but time constraints on my side do not allow to dig into it deeper at the moment. It will have some rough edges for time being.
But thank you for reporting it - definitely I will come back to things like that the future.

**Comment by ivandeex** [comment]
Adding runtime checks for all possible Windows breakages is hardly possible, but you can add a Troubleshooting (Installation) section in the README.md saying "if you can't see rclone section in the status bar, make sure rclone path in preferences is valid, does not point to a shared folder and rlone.exe is not owned by LocalSystem etc etc".
