### ISSUE TITLE
API Key and User Agent String

### ISSUE THREAD

**Issue by caspertone2003** [kapitainsky/RcloneBrowser#29]
Allow to include own API key for Gdrive
Allow to use user defined Agent String (--user-agent string)
(perhaps you can add a box to include rclone commands user specified... only needed to pass them to rclone...)
Save RCloneBrowser settings in portable .ini file 

Thanks!

**Comment by kapitainsky** [comment]
It is already supported. Look at extra options field in transfers. It can also be user pre defined in settings (default download/upload options)
