### ISSUE TITLE
interest in potential sync

### ISSUE THREAD

**Issue by caspertone2003** [kapitainsky/RcloneBrowser#3]
Fork from DinCahill
https://github.com/noabody/RcloneBrowser

**Comment by kapitainsky** [comment]
Can you tell me what does this fork you mentioned contain?

**Comment by kapitainsky** [comment]
If you think that something is worth adding create pull request and we can test it

**Comment by caspertone2003** [comment]
Sorry, lost track of this element...
Noabody fork is gone, so I close the issue...
I have the windows exe somewhere should you be interested in having a look to it.
CT
