### ISSUE TITLE
[Feature Request] Display folder size

### ISSUE THREAD

**Issue by TheFrenchGhosty** [kapitainsky/RcloneBrowser#30]
Right now the only way to see the size of a folder is to trigger "Get Size" manually on it.

I think it should be a good idea to have a setting that automatically do that in the background and update the UI accordingly.

**Comment by dia3olik** [comment]
This would be *really* nice!
But I think quite a bit heavy for the remote servers...no?
So maybe not on by default?

**Comment by kapitainsky** [comment]
Yes on big remotes it would be real slow. I am not planning to implement it now but if somebody does I can merge pull request.

**Comment by TheFrenchGhosty** [comment]
>But I think quite a bit heavy for the remote servers...no?
>So maybe not on by default?

Yes, this is why I suggested having a setting to do that, I don't know how cloud storage will react for people with thousands of folders

**Comment by kapitainsky** [comment]
I have tried to play with it and it is unfortunately disaster. Especially when there are many folders with a lot of files. Some people have read big data stores in 'the cloud'. I am not planning to implement it.
