### ISSUE TITLE
[Request] Please provide RPM packages or Flatpak (AppImage is fine too)

### ISSUE THREAD

**Issue by serovar** [kapitainsky/RcloneBrowser#31]

**Comment by kapitainsky** [comment]
I think in the future I will provide AppImage

**Comment by kapitainsky** [comment]
In the meantime you should compile it directly from source. Let me know if you need some help

**Comment by serovar** [comment]
Thanks, for now I'll use the official (outdated) package in Fedora official repos.

**Comment by kapitainsky** [comment]
I dropped a line to Fedora [package](https://apps.fedoraproject.org/packages/rclone-browser) maintainer - hopefully he can update it.

**Comment by serovar** [comment]
It does work wonderfully, thank you very much :)

Does this AppImage contain information on how the package can be updated, so that it can by autoupdated via AppImageUpdate? And do you know if it is possible to have the AppImage follow the system theme? Launching it with "-style=GTK" does the trick, but it's a manual solution.

**Comment by kapitainsky** [comment]
and re AppImageUpdate - not yet. You are the first user of my AppImage  release and I am already learning new stuff:) I will look into updates issue later

**Comment by serovar** [comment]
In this issue I proposed Flatpak rather than AppImage, as a universal solution, just because it solves this two problems (autoupdates and system theme, when you have the corresponding theme installed as flatpak), but it is not absolutely a problem, it is only my personal OCD with things and you already has been super kind and helpful, so thank you very much again :)

**Comment by kapitainsky** [comment]
and sorry for trouble but please re download AppImage. The initial one was missing some libraries. Quite steep learning curve for me:)
