### ISSUE TITLE
Jobs tab not showing all transfers

### ISSUE THREAD

**Issue by nagleaidan** [kapitainsky/RcloneBrowser#32]
#### Running RcloneBrowser 1.6.0 on Ubuntu 18.04 through the AppImage.

Even though the task has 4 transfers and in the output all 4 are shown, only 1-3 of the progress bars show up. When this was happening on small files that uploaded almost instantly, this behavior made sense, but the the current files take several minutes and sometimes show up but often don't. See -> https://imgur.com/x4pmibm for a screenshot of the behavior.

**Comment by kapitainsky** [comment]
Thanks for letting me know. I will have a look - maybe for some bizarre reason (or some special character in filenames) parser fails to grab some lines.

**Comment by nagleaidan** [comment]
Thanks for the quick response. I restarted the task and now all the transfers are showing up (granted, these are different files). If it happens again, I'll post the full filenames here to help you out.
BTW, I'm really loving your work so far, thanks for forking the repo and continuing development

**Comment by kapitainsky** [comment]
I looked into it and do not see any reason why it would not work. I am not saying that you are wrong but:

![x4pmibm](https://user-images.githubusercontent.com/15635386/68853293-8a831780-06d1-11ea-899b-05c520a7e506.png)

are you sure you are looking at the current transfer? On your screenshot I can see that you look at some past stats.

**Comment by nagleaidan** [comment]
I'm sure it is an issue. I've seen it many times recently and have a theory as to why. I've noticed that most (if not all) of the time it happens, the files being transferred after being shortened by rclone's info screen all have the same abbreviated names. See https://imgur.com/a/wyeylez

**Comment by kapitainsky** [comment]
Cheers! If your theory is right we are half way towards solving it.  Maybe it will require rclone output changes. It is definitely doable - they are good bunch of people.

**Comment by kapitainsky** [comment]
Yes you are right. Perfect. This is not a bug in Rclone Browser but simply rclone limitations at the moment. I will talk to rclone people to see if we could refine it by e.g. adding some sort of ID to every like of rclone verbose output transfer. It could be done with extra command like switch to keep actual verbose output intact if used by other people's scripts. For time being it is rclone limitation we have to live with.

**Comment by nagleaidan** [comment]
Thanks for your investigation and all your work on RcloneBrowser

**Comment by kapitainsky** [comment]
There is a way to fix it. have already prove of concept working. Will include proper fix in the next release

**Comment by kapitainsky** [comment]
will include full file name and ETA in tooltip when you hover cursor over progress bar. Any comments? See how it works now:

<img width="1088" alt="Screenshot 2019-11-17 at 18 54 11" src="https://user-images.githubusercontent.com/15635386/69012266-d4872a00-096b-11ea-9f16-42a3fbe401e1.png">

**Comment by nagleaidan** [comment]
Looks great, thanks for the fix

**Comment by dia3olik** [comment]
Thanks for this! I also think it would be great to have the option to use just the progress percentage aligned to the right for each file without the long progress bar or maybe just making the progress bar much much shorter, both solutions would help immensely with long filenames...

**Comment by kapitainsky** [comment]
Yes this would help but only up to the point… long file names can be real looooooong. As now it works any cosmetic changes I leave for the future as there are still some functionality issues to be addressed first.

**Comment by dia3olik** [comment]
gotcha
