### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by mcuix** [kapitainsky/RcloneBrowser#33]
A nice feature would be the option to change font size etc.

**Comment by kapitainsky** [comment]
Could you please explain in a bit more details what the issue is? I have not noticed any problems with actual font size - but obviously I can't test all possible environments and settings.

**Comment by mcuix** [comment]
My OS is Ubuntu 18.04, where the fonts in Qt er very small. Usually there is an option to increase font-size.

**Comment by mcuix** [comment]
I fixed it locally by `export QT_FONT_DPI=128`

**Comment by kapitainsky** [comment]
Thanks for comment. What is your monitor resolution?

I will enable high DPI scaling in the next release - it should help.

**Comment by mcuix** [comment]
My monitor resolution is 1920x1080.
