### ISSUE TITLE
rclone-browser crashes after start

### ISSUE THREAD

**Issue by mcuix** [kapitainsky/RcloneBrowser#35]
After fresh installation on Ubuntu 18.04` rclone-browser` starts then crashes.  Installed via apt.
Complains of being unable to find` tasks.bin`
```
~$ rclone-browser
qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: no
qt5ct: D-Bus global menu: no
```

**Comment by kapitainsky** [comment]
Can you try AppImage release?

**Comment by kapitainsky** [comment]
missing task.bin is not as issue - or at least shouldn't be. If no task was created yet the file is not present. if issue still persist please send me a screenshot of this error message.

**Comment by mcuix** [comment]
Tried the Appimage with the same results.

**Comment by mcuix** [comment]
I have now got it working. I did a purge of install files and then retried the AppImage, which starts OK.
