### ISSUE TITLE
Feature requerst: Import backup of rclone config file

### ISSUE THREAD

**Issue by mcuix** [kapitainsky/RcloneBrowser#36]
A useful feature would be the option to import a rclone config file on initial installation.

**Comment by kapitainsky** [comment]
but it should not be required. Both configuration and tasks files are stored in predefined locations so when you install new version of Rclone Browser they will be used. In case you would like to move configuration to new computer you either copy these files (I will update readme with details) or use Rclone Browser in portable mode - it was half supported in Windows, but with next release it will be fully supported including Linux and macOS.
