### ISSUE TITLE
Feature Request: Mac OS 10.13 High Sierra compatibility

### ISSUE THREAD

**Issue by sciblu** [kapitainsky/RcloneBrowser#37]
Just came across this program. Tried to install the program, but it is not compatible with Mac OS 10.13 High Sierra :(

Is there a  past version of RcloneBrowser that is compatible with Mac OS 10.13 High Sierra?

**Comment by kapitainsky** [comment]
Indeed current version works with Mojave and Catalina only. But now I have found the way how to keep latest OS features working (e.g. dark theme) and provide backward compatibility. The next release will work on anything down OS X Mavericks . It should be release in the next week or two.

**Comment by kapitainsky** [comment]
if you want here is the latest pre-release version working on all older macOS systems:

https://www.icloud.com/iclouddrive/0TXekZ4JL1TAANEGhM3IGReNQ#rclone-browser-1.6.0-409180a-macOS

**Comment by sciblu** [comment]
Thanks, will definitely try out the pre-release version.
