### ISSUE TITLE
Feature request: unknown CAs or self signed certificate

### ISSUE THREAD

**Issue by fdefilippo** [kapitainsky/RcloneBrowser#38]
using rclone client it is possible to use endpoint s3 with self signed certificates or using private CAs using the --no-check-certificate flag,  could you add it as an option to rclonebrowser as well?

thank you.

**Comment by kapitainsky** [comment]
Rclone Browser supports custom rclone options. Either you enter it for current job:

<img width="899" alt="Screenshot 2019-11-14 at 07 23 38" src="https://user-images.githubusercontent.com/15635386/68835413-e9379980-06af-11ea-969a-8f8f72921242.png">

or you can make it persistent by setting in preferences:

<img width="712" alt="Screenshot 2019-11-14 at 07 24 27" src="https://user-images.githubusercontent.com/15635386/68835415-e9d03000-06af-11ea-8f16-20f9f46bc0bf.png">

**Comment by kapitainsky** [comment]
I consider this option very niche and and don't see any point in including it as standard. Provided functionality allows you to use it if you really need. Also you can add your cert to trusted certificates on your OS if you want to avoid ignoring trust in rclone.
