### ISSUE TITLE
Feature Request: Show filesize on progress bar (hover?)

### ISSUE THREAD

**Issue by nagleaidan** [kapitainsky/RcloneBrowser#43]
Now that you fixed #32 (thanks a ton), I've finally been using RcloneBrowser without showing the full Rclone output and I've noticed one piece of information not available. In Rclone, it shows you 32%/5G. Nothing in RcloneBrowser lets you see the size of the individual files that are being uploaded. If you choose to add this feature, I could see implementation as either adding the file size on the progress bar at all times or only showing it in the tooltip that appears when you hover over one of the progress bars.

**Comment by kapitainsky** [comment]
what about if tooltip would have two lines
```
filanameblablablabla
54% /1.837M, 204.098k/s, 4s
```

**Comment by nagleaidan** [comment]
That'd work great for me

**Comment by dia3olik** [comment]
that would be a nice addition!

**Comment by kapitainsky** [comment]
Done

**Comment by kapitainsky** [comment]
I will release all latest updates later this week. When finished with testing dark mode for Windows and Linux.

**Comment by nagleaidan** [comment]
That was surprisingly fast! Do you have anywhere were I can buy you a coffee?

**Comment by kapitainsky** [comment]
it was just that I knew what to do here. So proffered just to do it

**Comment by kapitainsky** [comment]
you wait for release or compile yourself? if latter it is in kptsky_testing branch at the moment

**Comment by nagleaidan** [comment]
I compile. I'll test it quickly and let you know how it looks

**Comment by kapitainsky** [comment]
<img width="966" alt="Screenshot 2019-11-26 at 15 38 59" src="https://user-images.githubusercontent.com/15635386/69648334-016dc800-1063-11ea-86ee-860fddd96888.png">

**Comment by kapitainsky** [comment]
Wait a moment. I will add dark mode to testing branch. you can have a look and maybe comment

**Comment by kapitainsky** [comment]
done. you can enable dark mode in prefferences

**Comment by nagleaidan** [comment]
Looks good on Ubuntu 18.04
![](https://user-images.githubusercontent.com/15807611/69649568-39f9ab80-103b-11ea-8ad7-3b41765ba614.png)
