### ISSUE TITLE
Deb distribution

### ISSUE THREAD

**Issue by marcheschi** [kapitainsky/RcloneBrowser#44]
Hi
I noticed the absence of .deb package.

Can you Add it to the release?
Thank you
Paolo

**Comment by kapitainsky** [comment]
Please see explanation why I don't provide deb here https://github.com/kapitainsky/RcloneBrowser#how-to-get-it

You can download AppImage make it executable and run. If you for whatever reason don't like it I provide detailed instructions how to build it yourself - it is very easy and quick.

**Comment by kapitainsky** [comment]
I assume that deb provided earlier worked for you but it did not for others. I don't want to fight with different dependencies in different distributions. AppImage solves this problem. 

If you would like it more closely integrated with your particular distro you can contact maintainers of your distribution and ask them to add Rclone Browser to their repositories.

**Comment by marcheschi** [comment]
Thank you, for your fast reply.
The app worked fine with linux mint, Now it works also with appimage, but it is not integrated in the desktop.
I will try to build myself
Best regards
Paolo

**Comment by kapitainsky** [comment]
It can be very easy integrated with Desktop.

Have a look at  AppImageLauncher:

https://www.linuxuprising.com/2018/04/easily-run-and-integrate-appimage-files.html

https://manjaro.site/how-to-install-appimage-launcher-on-ubuntu-19-04/

**Comment by kapitainsky** [comment]
> Thank you, for your fast reply.
> The app worked fine with linux mint, Now it works also with appimage, but it is not integrated in the desktop.
> I will try to build myself
> Best regards
> Paolo

If you would have any issue with building it let me know. I will update instructions. I have not tried building on mint but I assume it falls into Ubuntu/Debian category

**Comment by marcheschi** [comment]
Hi
I tried to install packages on mint in order to compile it, but  I receive these errors:
sudo apt install libQt5Core-devel libQt5Widgets-devel libQt5Network-devel
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libQt5Core-devel
E: Unable to locate package libQt5Widgets-devel
E: Unable to locate package libQt5Network-devel


However your suggestion on using appimagelauncher Is right and Now I have rclone browser successfully integrated. This is also useful for other appimage softwares.
Thank you
Paolo

**Comment by kapitainsky** [comment]
because these are packages names in Suse Linux....
Mint is Ubuntu/Debian family so you should only run

`sudo apt update && sudo apt -y install git g++ cmake make qtdeclarative5-dev`

**Comment by marcheschi** [comment]
Yes
Sorry for that the command  belongs to a series of retries i did to install the right package.
I think it is my  distro state that cause the error.

 sudo apt install git g++ cmake make qtdeclarative5-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version (4:5.3.1-1ubuntu1).
g++ set to manually installed.
make is already the newest version (4.1-6).
cmake is already the newest version (3.5.1-1ubuntu3).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 git : Depends: libcurl3-gnutls (>= 7.56.1) but 7.47.0-1ubuntu2.14 is to be installed
       Depends: libpcre2-8-0 (>= 10.31) but it is not going to be installed
 qtdeclarative5-dev : Depends: qtbase5-dev
E: Unable to correct problems, you have held broken packages.

**Comment by kapitainsky** [comment]
yes... if installing git fails something is messed up.  you hold some outdated packages. 

This is one of the reasons I switch to AppImage. I want to provide something simple working for everyone. I also do Windows and macOS releases. Not possible to cover particular Linux distros - especially that there many.

**Comment by marcheschi** [comment]
This is right 
Now I understand.
Thank you for your patience.
And thank you for your effort,
Rclone and Rclone browser are Killer applications !!
Best regards
Paolo

**Comment by kapitainsky** [comment]
And actually building on Mint works - I forgot that it was the first issue I faced.

See #1
