### ISSUE TITLE
creating a launcher for the appImage

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kapitainsky/RcloneBrowser#45]
You have quite a bit of documentation on the appImage format. However, I find it hard to know to create a menu launcher on my system for your appImage. I found [some instructions](https://forums.linuxmint.com/viewtopic.php?t=273402) elsewhere and they worked but seem inelegant and I wonder whether I have done things the best way. I do appreciate that procedures will differ between different Distos and DEs . .

**Comment by kapitainsky** [comment]
Have a look at AppImageLauncher:

https://www.linuxuprising.com/2018/04/easily-run-and-integrate-appimage-files.html

**Comment by kapitainsky** [comment]
To have it nicely integrated with your Linux the best option is to contact your distro maintainers and ask them to include Rclone Browser in your distribution "shop".

This is what Arch Linux guys are doing:

https://aur.archlinux.org/packages/rclone-browser

I guess in day or two they will update to 1.7.0 and all Arch Linux users receive update automatically

**Comment by LinuxOnTheDesktop** [comment]
That program is a god-send. Distros should have it installed by default. Thank you.

**Comment by kapitainsky** [comment]
I want to focus on Rclone Browser functionality. I also release it for macOS and Windows. This is why I can't deal with 10000 different Linux distros. AppImage is the best option I found to solve the mess.

If people like Rclone Browser they can push their distro maintainers to include it natively.

**Comment by LinuxOnTheDesktop** [comment]
I find that AppImageLauncher has bugs and so far as I can tell no way to report them (unless one counts an almost deserted Reddit forum . .). So perhaps you should not recommend it.

**Comment by kapitainsky** [comment]
report here:

https://github.com/TheAssassin/AppImageLauncher

guy is very responsive

**Comment by kapitainsky** [comment]
and some bug is not a reason not to use it:) I use phone which receives bug fixes every month or so meaning it has bugs all the time:)

**Comment by kapitainsky** [comment]
you can see maybe already fixed in continues build:

https://github.com/TheAssassin/AppImageLauncher/releases/tag/continuous

**Comment by LinuxOnTheDesktop** [comment]
Proprietary software, especially on phones, gets updates (or 'updates') to keep one using the product, not so much to fix bugs. :) But I take your point. It's just the software looked abandoned. I'm glad it isn't. I have filed a bug report. Thanks for your help.

**Comment by kapitainsky** [comment]
No no it is not abandoned. Actually there is a lot of work going on there and around AppImage tools.

You are right with phones - I would not used one that does not receives fixes:)
