### ISSUE TITLE
Default additional flags

### ISSUE THREAD

**Issue by Dibbyo456** [kapitainsky/RcloneBrowser#46]
So, basically I wants to use the `--fast-list` flag all the time as well as when listing directories.
Right now, RcloneBrowser only allows to set additional flags for Uploads and Downloads only.

A option to set additional flags for every time (including directory listing) would be very helpful.

**Comment by kapitainsky** [comment]
rclone has 377 possible flags (`rclone help flags . | wc -l`) and I have not looked at all of them. There is always something new. Thanks for pointing this option out.

I think your request makes sense and is easy to implement. I will add additional default (include in all rclone operations). Then you could put `--fast-list` there

**Comment by Dibbyo456** [comment]
> I think your request makes sense and is easy to implement. I will add additional default (include in all rclone operations). Then you could put `--fast-list` there

Great..! Thank you for the quick reply. Perhaps you can add the `--fast-list` flag for every possible actions (listing, copy, sync etc).

Because according to the [docs](https://rclone.org/docs/#fast-list): "If you use `--fast-list` on a remote which doesn’t support it, then rclone will **just ignore it**." So, adding it to the default flags won't do any harm. 😃

**Comment by kapitainsky** [comment]
yes but instead of hardcoding it I will make it configurable with `--fast-list` as a default. Maybe there are other similar options or there will be in the future. This way user can decide what to use

New default will be applied to all rclone operation.

**Comment by kapitainsky** [comment]
It has been fixed in the [latest release](https://github.com/kapitainsky/RcloneBrowser/releases/tag/1.8.0)
