### ISSUE TITLE
Portable package for windows

### ISSUE THREAD

**Issue by caspertone2003** [kapitainsky/RcloneBrowser#48]
@kapitainsky 
Thanks again for transforming a zombie sw into a real alive program!

Last 1.7.0 changed the windows version, replacing  the zip package by an installer.
Unfortunately, some users cannot install programs and the installation modifies the registry.

Workaround is to install in another machine, zip the folder to transport to another computer, and remove the installation.

Could you please retain the zip package in the distribution?

Thanks for considering!
CT

**Comment by kapitainsky** [comment]
You can always install for current user only. It does not require admin rights. Copy files and then uninstall. 

Or extract files from installer using e.g.

https://constexpr.org/innoextract/


There are so few users who need it that I consider it misleading for others to have exe and zip files released.

**Comment by caspertone2003** [comment]
Understood.
Good reference to innoextract, perhaps add it to the information page?
CT

**Comment by kapitainsky** [comment]
Do you still have problem with tasks file not being saved in the same folder as binary in portable mode?

**Comment by kapitainsky** [comment]
> Good reference to innoextract, perhaps add it to the information page?

Will add. good point
