### ISSUE TITLE
Possible use of very old version of 'arrow' python package

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kapitainsky/RcloneBrowser#5]
Hello!

pip shows me this:

`b2sdk 0.1.8 has requirement arrow<0.13.1,>=0.8.0, but you have arrow 0.14.6.`

Does `b2sdk` owe to your version of rclone-browser? I'm using your version of rclone-browser with `arrow` 0.14.6 and everything works. Perhaps I do not need `b2sdk` - and even `arrow` too? - at all. Thanks.

**Comment by kapitainsky** [comment]
b2sdk is not used by rclone-browser. It is Python library used to access B2 cloud storage. rclone is golang application so I am not sure where you have this message from? In what context you invoke pip?

**Comment by LinuxOnTheDesktop** [comment]
Thanks. I saw the message when I ran

`$ pip check`

I use B2 storage with rclone and thus with rclone-browser and with nothing else. Ah: I think that at one point I tried to use B2 storage using B2's own tool, namely a python tool called, er, `b2'. I've removed `b2` and `b2sdk` and rclone and rclone-browser run fine. So, I have closed this issue.
