### ISSUE TITLE
User experience improvement

### ISSUE THREAD

**Issue by caspertone2003** [kapitainsky/RcloneBrowser#53]
Hi,
I discovered this by chance - https://github.com/MinorMole/RcloneBrowser-Portable

Some interesting points are in place, wonder if you two could share forces...

Cheers
CT

**Comment by kapitainsky** [comment]
Quite cool.

This app is already using my fork (previous version - 1.6.0) even though in readme he refers to another fork.

If he notices that new version is available maybe will update it. 

There are no contact details provided and reporting issues is disabled -  no contactable individual:)

**Comment by kapitainsky** [comment]
I also don't like that this app downloads all required binaries including rclone browser not from their original sources but from hosted zip file. All probably fine but it can include anything...

**Comment by caspertone2003** [comment]
Then... you may import any cool element from its source code without any kind of remorse...

**Comment by kapitainsky** [comment]
it is windows only and I insist on providing the same functionality across all supported platforms so code itself is not very useful. In terms of idea to bundle everything (rclone, fuse and rclone-browser) I don't want to manage 3rd parties dependencies from within the browser but I agree that at the moment some users might be not clear what is needed.  I will definitely try to make it more user friendly - pop up with instructions or similar.

**Comment by caspertone2003** [comment]
Thanks!
