### ISSUE TITLE
bandwidth limiting

### ISSUE THREAD

**Issue by whatistime** [kapitainsky/RcloneBrowser#54]
Is it possible to limit the bandwidth, either up/down after the copy/move/sync has started? 

Sometimes I'll start a transfer, but I don't set a bandwidth limit, because I don't anticipate something else needing all my immediate bandwidth in a particular direction.  Or rather, I'd like a particular transfer to compete less with my ongoing RcloneBrowser transfer.  It would be nice to be able to limit bandwidth almost on the fly, maybe after the next next finished file would be perfect!  

Thank you,
whatistime.

**Comment by kapitainsky** [comment]
Rclone itself does not have such functionality. But with Rclone Browser you could save your transfer as a task and in case you need bandwidth changes just stop the job, modify tasks parameters and start it again.
