### ISSUE TITLE
Automatically quote exclude file when Space in file path

### ISSUE THREAD

**Issue by Rhilip** [kapitainsky/RcloneBrowser#56]
When I use the Exclude options to download files, I find some file with space in file path can't be success excluded from transfering.
For example, A file named `abcd txt.txt`

![image](https://user-images.githubusercontent.com/13842140/71180109-7c19b400-22ac-11ea-97b0-065a2f02e9e0.png)

The generated command of rclone will be like
```
rclone.exe copy --verbose --transfers 4 --checkers 8 --contimeout 60s --timeout 300s --retries 3 --low-level-retries 10 --exclude abcd txt.txt --drive-acknowledge-abuse --stats 1s --stats-file-name-length 0 src: des:
```

It seems wrong since the file which path is `abcd` and `txt.txt` will be exclued, And what we real want is `abcd txt.txt`. So In my options, Each line should be quote so It can work as we expected. like this commands:

```
rclone.exe copy --verbose --transfers 4 --checkers 8 --contimeout 60s --timeout 300s --retries 3 --low-level-retries 10 --exclude "abcd txt.txt" --drive-acknowledge-abuse --stats 1s --stats-file-name-length 0 src: des:
```

**Comment by kapitainsky** [comment]
Ok. Noted. Definitely if this is the case I will fix it. 

In the meantime you can specify exclude in extra options or use exclude file. 

Rgds

Dariusz

**Comment by kapitainsky** [comment]
Also you can specify file names with spaces with quotes then generated rclone command should be ok. 

Rgds

Dariusz

**Comment by kapitainsky** [comment]
I am not sure if it should be fixed. I think it is better when user specifies exclusion names exactly how would do with rclone. So if names with spaces have to be excluded they have to be listed in quotes. 

What you think?

**Comment by Rhilip** [comment]
Yes, You are right.
Now I quote each line manually, so it can be worked as I excepted.
Maybe a Instructions for use in this dialog will be better.

**Comment by kapitainsky** [comment]
Yes in the next release I will provide tool tips with explanation.  It is not clear enough at the moment how to use it.

**Comment by kapitainsky** [comment]
It has been fixed in the [latest release](https://github.com/kapitainsky/RcloneBrowser/releases/tag/1.8.0)
