### ISSUE TITLE
Cannot setup new connections to cloud services within RcloneBrowser

### ISSUE THREAD

**Issue by Darthagnon** [kapitainsky/RcloneBrowser#57]
I click on "Config..." under the Remotes tab, a CMD window flashes onscreen then disappears. Isn't that button meant to bring up configuration options for cloud services?

**Comment by kapitainsky** [comment]
Yes. This is what is supposed to happen. 

What OS you are on?

Could you please let me know what is your path to rclone executable and rclone configuration file?

**Comment by abunavas** [comment]
I have the same problem + 

I already have created configs for OneDrive using instructions from here https://rclone.org/onedrive/. 
No remotes shown on rclone browser

I am on Win 10  Pro 1909, latest rclone and rclone browser 1.7.0 64 bit

![1](https://user-images.githubusercontent.com/11981078/71556256-4dcb6f80-2a36-11ea-85bf-b3cd663e30bf.jpg)

**Comment by kapitainsky** [comment]
Do you have in preferences path  specified to both rclone executable and rclone config? Given that everything works for majority of users I suspect some configuration issue.

**Comment by kapitainsky** [comment]
I can see from your screenshot that rclone.exe is configured and works so only culprit left is rclone config file.

**Comment by abunavas** [comment]
> I can see from your screenshot that rclone.exe is configured and works so only culprit left is rclone config file.

Thank you for fast answer. I suppose that I config correct. 

![2](https://user-images.githubusercontent.com/11981078/71556402-92f0a100-2a38-11ea-8c04-55c11883dd17.jpg)

**Comment by kapitainsky** [comment]
All clear now. No it is not correct. 
rclone.1 file is some rclone program file not configuration. 
You have to specify rclone.conf file location. 
On windows by default rclone saves it in your user folder:

C:\Users\username\.config\rcone\rclone.conf

If you have not changed default location you can simply clear any path from preferences.

**Comment by kapitainsky** [comment]
On windows if configuration path is not specified rclone uses default location. You don’t have to explicitly specify it.

**Comment by abunavas** [comment]
Ups, my mistake. All working now. Thank you!

**Comment by Darthagnon** [comment]
rclone.conf is saved in a weird location on my PC (some glitch caused by OrCAD Cadence changing the Home directory), and I had mapped that location in the rclone browser settings. That didn't work. Deleting the reference, so it uses the default works perfectly, though :) Thank you for the help!
