### ISSUE TITLE
Feature request: Local caching of files and folders

### ISSUE THREAD

**Issue by Qubits01** [kapitainsky/RcloneBrowser#58]
Hi,
It'd be great if the program could cache the files and folders locally so it doesn't have to redownload all the info every time it's restarted.
This would make browsing so much faster.
You could add a "refresh" button to refresh the current dir when needed.

Edit: of course I only mean filenames, not the actual files.

**Comment by kapitainsky** [comment]
if you require heavy browsing you could try to mount remote using optimization discussed in this thread:

https://forum.rclone.org/t/how-to-get-full-directory-tree-cached-on-first-mount/12535

I try to keep Rclone Browser as universal and simple as possible and remotes content caching unfortunately is not straightforward. Only would work reliably for remotes with functionality to advertise remote filesystem changes (which ones they are? there are new added all the time). Without it local cache can very easily be in no sync (especially for remotes accessible by multiple users). It would be very specific solution for very few users.

**Comment by kapitainsky** [comment]
There is no safe way to implement it. There is no guarantee that remote content remains the same between application restarts. It would solve very specific issue only and does not work universally.
