### ISSUE TITLE
no icon for application gui [resolved]

### ISSUE THREAD

**Issue by jerome-diver** [kapitainsky/RcloneBrowser#59]
Hi, i can not find any icon for this application. Maybe there is one, but where please ?

**Comment by kapitainsky** [comment]
I am not sure what your issue exactly is. If you need Rclone Browser icon for something grab one from https://github.com/kapitainsky/RcloneBrowser/tree/master/assets

**Comment by kapitainsky** [comment]
These are icons used for Rclone Browser app:
Windows - https://raw.githubusercontent.com/kapitainsky/RcloneBrowser/master/src/icon.ico
macOS - https://github.com/kapitainsky/RcloneBrowser/blob/master/src/icon.icns
for Linux it is set of icons (png and svg) from: https://github.com/kapitainsky/RcloneBrowser/tree/master/assets

There are all included in relevant OS releases.

**Comment by jerome-diver** [comment]
Hi @kapitainsky, yes that's it, you perfectly understand what i was asking for.
Mine (rclone-browser) is installed from archlinux AUR repo and unfortunately, icon is not in good place , and find command didn't find it too...
Thank you very much, now i get it because of your link.

**Comment by kapitainsky** [comment]
I would suggest you contact Arch package maintainers:

https://aur.archlinux.org/packages/rclone-browser

They should fix icon issue in their package.
