### ISSUE TITLE
Make verbose output option permanent.

### ISSUE THREAD

**Issue by kapitainsky** [kapitainsky/RcloneBrowser#6]
As without verbose output checked no info is available to show sync progress, I will remove this option from GUI and make it permanently set.

I found it annoying when for whatever reason it is left unchecked and I start sync job. Can’t see what’s going.

I don’t see any reason to run rclone via rclone-browser without verbose output.

**Comment by kapitainsky** [comment]
included in 1.5 release

**Comment by chriscrox** [comment]
Hi, @kapitainsky. Under "Export" there's also and option to show Verbose Output. However, both with it selected and wihtout it selected, verbose output is shown, so is it possible to remove the box as it no longer has a use? Thank you very much. :)

**Comment by kapitainsky** [comment]
Well spotted! I missed it when I was removing this option from transfers. 

It will be gone in the next release
