### ISSUE TITLE
SFTP - RcloneBrowser defaults to different directory than rclone and SSH

### ISSUE THREAD

**Issue by msalini** [kapitainsky/RcloneBrowser#64]
I have a SFTP/SSH remote. When I open it with Rclone Browser, it defaults to the root directory ("/") while when I SSH to it, or I ``rclone lsd remote:`` , it defaults to the correct directory ``/home/user``.

Any idea as to why RcloneBrowser does not follow the correct behaviour of rclone and ssh?

**Comment by kapitainsky** [comment]
Because it uses remote:/ as a root folder. Does it make difference?

**Comment by kapitainsky** [comment]
As I remember there was an issue with Synology sftp access without leading /. It works for other sftp servers as well so it was good compromise.

**Comment by msalini** [comment]
Unfortunately I am on a shared server, so I cannot browser from / to /home (no permission) to /home/user (permission).
Until you implement the "Go to" button to jump directly to the intended path, I am "stuck" in root with RcloneBrowser.

**Comment by msalini** [comment]
> Because it uses remote:/ as a root folder. Does it make difference?

Between ``remote:`` and ``remote:/`` there is quite a difference. Why is t not possible to the remove the slash "/". That would solve the issue.

**Comment by kapitainsky** [comment]
Than it will break synology sftp. But I see your point and issue you are facing.

**Comment by kapitainsky** [comment]
Ok. Definitely something to fix. I have to think how to do it.

**Comment by msalini** [comment]
> Ok. Definitely something to fix. I have to think how to do it.
> […](#)
> On 9 Jan 2020, at 11:07, msalini ***@***.***> wrote: ﻿ Unfortunately I am on a shared server, so I cannot browser from / to /home (no permission) to /home/user (permission). Until you implement the "Go to" button to jump directly to the intended path, I am "stuck" in root with RcloneBrowser. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for the swift reply! :-)

**Comment by kapitainsky** [comment]
I will check synology situation. If they fixed / issue the easiest will be to default to standard ssh/rclone behaviour

**Comment by kapitainsky** [comment]
It has been fixed in the [latest release](https://github.com/kapitainsky/RcloneBrowser/releases/tag/1.8.0)

**Comment by runapp** [comment]
Now we just can't navigate outside default directory. Comparing with other SFTP clients, usually they will call `pwd` once logged in and show the directory structure in the tree view.
