### ISSUE TITLE
disable SSL check on HTTP remotes

### ISSUE THREAD

**Issue by zeebarb** [kapitainsky/RcloneBrowser#65]
i have an http remote and it does not load in rclone browser due to invalid SSL certificate. this was addressed in rclone with https://github.com/rclone/rclone/issues/168 and `--no-check-certificate`. was wondering if it would be implemented optionally in http remotes. thank you

**Comment by kapitainsky** [comment]
In the next release I will add configurable rclone parameters for all operations - then you can use it to specify --no-check-certificate option. 

It is the same type of issue as already reported in #46

**Comment by kapitainsky** [comment]
It has been fixed in the [latest release](https://github.com/kapitainsky/RcloneBrowser/releases/tag/1.8.0)

Please use "Default rclone options" filed in preferences to specify --no-check-certificate
