### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by parqbanq** [kapitainsky/RcloneBrowser#66]
The app is really small now..., please provide HiDPI support.

**Comment by kapitainsky** [comment]
What is your screen resolution? and what OS you are on?

**Comment by parqbanq** [comment]
Ubuntu 18.04.3

![Screenshot from 2020-01-13 19-06-28](https://user-images.githubusercontent.com/55151851/72280240-2da3cf00-3638-11ea-9eca-052dffd0ea5c.png)

![Screenshot from 2020-01-13 19-10-46](https://user-images.githubusercontent.com/55151851/72280380-7b203c00-3638-11ea-8963-2c6d35050dd0.png)

**Comment by kapitainsky** [comment]
Try by setting this environment variable:

export QT_FONT_DPI=128

I don’t know atm how to fix this cross platform. Hopefully in the future some better solution will be found.

**Comment by parqbanq** [comment]
Looks like this:

![Screenshot from 2020-01-13 19-16-52](https://user-images.githubusercontent.com/55151851/72280734-4a8cd200-3639-11ea-8379-9c8f019a88dd.png)

**Comment by kapitainsky** [comment]
Yes. Agree. This is not good

**Comment by parqbanq** [comment]
Ah, we crossed! I will try your suggestion now!!

**Comment by parqbanq** [comment]
I mean after diner..., I 'll be back...

**Comment by parqbanq** [comment]
I set ```export QT_FONT_DPI=128``` in ```~/.bashrc``` but the problem remains.

**Comment by kapitainsky** [comment]
Can you double check it is set? When I set it from cmd and then run RCB all fonts are bigger. You can also set higher number than 128

**Comment by parqbanq** [comment]
Ah, yeah, it works! I set it to 199 and now:
![Screenshot from 2020-01-13 21-18-51](https://user-images.githubusercontent.com/55151851/72288934-63ea4a00-364a-11ea-9e3d-2250cd2c6b76.png)

Nice!

**Comment by kapitainsky** [comment]
Sorry it is not hassle free. But it is quite complex problem to tackle from working the app with a lot of legacy code.

**Comment by parqbanq** [comment]
There are quite a lot of apps that have problems dealing with HiDPI  actually...; I am really happy I can use RcloneBrowser now! Thanks for helping out!!

**Comment by kapitainsky** [comment]
Hi, I need small help:) in the next release I am will include more options to adjust interface size (fonts, buttons and remotes' icons). Unfortunately I don't have access to HiDPI monitor at the moment. Would you mind to try pre-release version and let me know if font sizes I chose (especially Large and Extra Large) are sufficient for monitor like yours?  If you could try without any QT_FONT_DPI exported - you can unset it by running `unset QT_FONT_DPI`

My objective would be to make sure that font size L is perfect for your resolution and XL would be good for even higher.

Here you are link for latest development AppImage version for Linux:

https://1drv.ms/u/s!Aq335pidOrBV38Z49iGD7cMMuYNNgA

**Comment by kapitainsky** [comment]
Interface elements size can be changed in the new preferences window:

<img width="863" alt="Screenshot 2020-02-23 at 12 08 11" src="https://user-images.githubusercontent.com/15635386/75111761-4fc83e00-5635-11ea-9af5-42b12ec4685c.png">

**Comment by rapejim** [comment]
Hi @kapitainsky,

I use a 27" UHD monitor, but I use your rclone browser on Windows, if you want I can test "beta"/prerelease versions on my PC.
