### ISSUE TITLE
--max-transfer

### ISSUE THREAD

**Issue by Spelvi** [kapitainsky/RcloneBrowser#67]
Is there a way to use --max-transfer for the 750GB limit of Google Drive?

**Comment by kapitainsky** [comment]
Yes. Assuming that you refer to upload limit add this to default upload options in preferences:

<img width="824" alt="Screenshot 2020-01-15 at 17 16 23" src="https://user-images.githubusercontent.com/15635386/72455537-dc701880-37ba-11ea-8478-f4c1df1f9f7b.png">

**Comment by Spelvi** [comment]
Perfect! Thank you very much Kapitainsky.
