### ISSUE TITLE
Bandwidth box on Jobs tab is too small

### ISSUE THREAD

**Issue by renzzla** [kapitainsky/RcloneBrowser#68]
I'm running RcloneBrowser on a seedbox that has a 20Gb/s network connection, and so I can get some very fast speeds. When the bandwidth exceeds 100MB/s (yes, megabytes), the box on the "Jobs" page for each job is too small, and the leading '1' is hidden. As it is, the Bandwidth box can only show bandwidth up to 99.999 MB/s. Could it be increased in size in the next release please?

**Comment by kapitainsky** [comment]
Great problem to have:)

Indeed I have not planned for such speed but no problem - I will make this field bigger to cover speeds up to 999.999 MB/sec

**Comment by kapitainsky** [comment]
Could you please send me a screenshot of Jobs page when Bandwidth field is not big enough?
I dont have connection fast enough to check myslef

**Comment by renzzla** [comment]
Here you go - this was running at 126MB/s

![Capture](https://user-images.githubusercontent.com/7829654/72612461-c0888600-3924-11ea-9068-5ad779f17967.JPG)

**Comment by kapitainsky** [comment]
ok. it will look correct in the next release

**Comment by kapitainsky** [comment]
it has been updated. If you need it now you can compile it from kptsky_testing branch. Or wait for next release. I think I will do one in 2-3 weeks

**Comment by renzzla** [comment]
I'll wait for the next release. Thanks for looking at it so quickly!

**Comment by kapitainsky** [comment]
It has been fixed in the [latest release](https://github.com/kapitainsky/RcloneBrowser/releases/tag/1.8.0)
