### ISSUE TITLE
Does not work with encrypted config

### ISSUE THREAD

**Issue by ribtoks** [kapitainsky/RcloneBrowser#69]
Hi @kapitainsky 

Thanks working on this app!

Unfortunately I cannot use it with encrypted rclone config. When I open this browser, I see 3 buttons on 1st tab: "Refresh", "Config..." and something else. When I press "Refresh" nothing happens. When I press "Config..." I get a console window that asks for my password. After I enter password and press enter, nothing happens, I only get list of remotes (in console). If I quit `rclone config` (that is started in console) using `q`, nothing happens too. Also if I close console window, nothing happens as well...

Is it a bug or I'm doing something wrong?

**Comment by kapitainsky** [comment]
When using encrypted rclone conf file after starting Rclone Browser you should be asked for its password:

<img width="1181" alt="Screenshot 2020-02-05 at 08 37 35" src="https://user-images.githubusercontent.com/15635386/73815221-1acf8500-4807-11ea-831b-08f4e953a9b9.png">

then everything should work as usual.

I would suspect that you have not provided correct rclone config file path in settings.
Make sure that it points to your encrypted config file:

<img width="824" alt="Screenshot 2020-02-05 at 11 07 31" src="https://user-images.githubusercontent.com/15635386/73815419-c8429880-4807-11ea-913c-b089199911be.png">

**Comment by ribtoks** [comment]
Thanks, I'll try later at home

**Comment by kapitainsky** [comment]
Did it work?

**Comment by ribtoks** [comment]
Sorry, I was busy. So far I'm not using RcloneBrowser, cannot confirm.
