### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by Lonli-Lokli** [kapitainsky/RcloneBrowser#70]
Is there any docker version?
I have a NAS with docker support and with media server inside so for me it will be useful to have Docker version mounted to host.

**Comment by kapitainsky** [comment]
I do not provide docker version. I believe it should be relatively easy to build your own docker version if needed.

**Comment by kapitainsky** [comment]
there is now updated docker version provided by @romancin

https://github.com/romancin/rclonebrowser-docker
