### ISSUE TITLE
1.8 release does not start on Fedora 31

### ISSUE THREAD

**Issue by serovar** [kapitainsky/RcloneBrowser#75]
The x86_64 version of the new 1.8 release does not start on Fedora 31. I get this error:
```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

**Comment by kapitainsky** [comment]
hmmmm.. let me look into it

**Comment by kapitainsky** [comment]
Good thing is that Rclone Browser is now officially included in Fedora repos

https://apps.fedoraproject.org/packages/rclone-browser

So hopefully they will catch up with the latest version soon

**Comment by kapitainsky** [comment]
I found the issue. Latest release of AppImage creation tools contains some weird bug... 

I will update release soon with working AppImages (created using previous tools)

**Comment by renzzla** [comment]
I'm getting exactly the same thing on a Debian-based server using the X86_64 AppImg. The previous Appimg version worked fine.

**Comment by kapitainsky** [comment]
I have swap AppImages for Linux with ones generated using previous versions of AppImages tools. 

Could you let me know if they work now?

**Comment by renzzla** [comment]
Working ok for me now - thanks!

**Comment by kapitainsky** [comment]
FYI - I reverted to previous versions of AppImage tools (and updated released AppImage files) and raised the issue with their author linuxdeploy/linuxdeploy-plugin-qt#65.

**Comment by serovar** [comment]
Works for me too, thanks :)

**Comment by kapitainsky** [comment]
Thanks for reporting!
