### ISSUE TITLE
Change app icon to new rclone logo

### ISSUE THREAD

**Issue by mstgrv** [kapitainsky/RcloneBrowser#8]
Firstly, massive thanks for pushing things forward with this app!

Would be great if the app icon could be changed to the updated rclone logo, more details here:

https://forum.rclone.org/t/a-new-logo-for-rclone/7019
https://github.com/rclone/rclone/tree/master/graphics/logo

**Comment by kapitainsky** [comment]
Good idea - will look into it. Would be nice to impose rclone-browser text on it.

**Comment by kapitainsky** [comment]
<img width="108" alt="Screenshot 2019-09-23 at 11 08 36" src="https://user-images.githubusercontent.com/15635386/65417679-84b83680-ddf2-11e9-917a-5974df7c667c.png">

What you think?

**Comment by kapitainsky** [comment]
I think this is one I like

![rclone-second-path](https://user-images.githubusercontent.com/15635386/65422923-aa980800-ddff-11e9-8070-efe2aa60720c.png)

**Comment by kapitainsky** [comment]
![rclone-second-path](https://user-images.githubusercontent.com/15635386/65423194-5b060c00-de00-11e9-8202-db4e72778a63.png)

or this one with transparency

**Comment by kapitainsky** [comment]
or this one...

<img width="108" alt="Screenshot 2019-09-23 at 12 56 12" src="https://user-images.githubusercontent.com/15635386/65423708-a967da80-de01-11e9-8730-b65f4b04989a.png">

**Comment by mstgrv** [comment]
You could maybe use one of the options which has the Rclone text in it already, and just add Browser to the bottom?

https://github.com/rclone/rclone/tree/master/graphics/logo/logo_on_light
