### ISSUE TITLE
Selectable terminal emulator

### ISSUE THREAD

**Issue by TruckerZer0** [kapitainsky/RcloneBrowser#81]
Let me first say hello and thank you for all the efforts you are making to keep this little gem alive and improve it, I have only one small request, if possible: it would be possible to include in the options the possibility of being able to change the terminal used in order to match the desktop environment in use?

Thanks again and keep up the great work!

**Comment by kapitainsky** [comment]
This is the order RB tries terminals: - $TERMINAL then gnome-terminal followed by xfce4-terminal, xterm, x-terminal-emulator and konsole

so set $TERMINAL variable in your environment to one you prefer. otherwise first working is used

**Comment by kapitainsky** [comment]
I will add tooltip to "Config" button explaining it in the next release.

**Comment by TruckerZer0** [comment]
I didn't know, I'm on KDE Plasma, and at least the appimage version keeps opening Xterm ivece of Konsole...

**Comment by kapitainsky** [comment]
you can always just run config from command line - just `rclone config`. Usually it is done so rarely that should not be bug deal.

**Comment by TruckerZer0** [comment]
Well, that's what I actually did, but it bothered me a little; Thanks anyway!
