### ISSUE TITLE
Add "Trash" checkbox that show files from Google Drive Trash

### ISSUE THREAD

**Issue by thanamaha2002** [kapitainsky/RcloneBrowser#82]
I think this is an easy implementation just copy the checkbox "Shared" that show file from Shared with Me in Google Drive.

<img width="720" alt="01" src="https://user-images.githubusercontent.com/35872889/75221444-6e187000-57d4-11ea-9c1e-61caf1094dc6.png">

The idea of the "Trash" checkbox is to show a file from Google Drive Trash using this argument.

[--drive-trashed-only](https://rclone.org/drive/#drive-trashed-only)

<img width="720" alt="03" src="https://user-images.githubusercontent.com/35872889/75221668-fbf45b00-57d4-11ea-87e1-9d4496d69925.png">

**Comment by thanamaha2002** [comment]
Or even better design you can use the combo-box with 3 options. It also avoids the issue that you can check 2 check-boxes at the same time.

Combo-box option:
- My Drive
- Shared with Me
- Trash

**Comment by kapitainsky** [comment]
does rclone supports transfers from Google  Drive Thrash?

**Comment by thanamaha2002** [comment]
> does rclone supports transfers from Google Drive Thrash?

Yes, you can download files from trash or delete it (it will permanently be deleted if you delete a file from trash via rclone.)

You can try setting up the remote by edit rclone.conf like this

`[Google Drive]
type = drive
scope = drive
trashed_only = true
token = xxx`

Don't get confused with the directory, it will show the current directory from My Drive but if you navigate the directory only file in the trash will show up and you can pretty much anything with it.

**Comment by thanamaha2002** [comment]
I actually set up the remote for the trash but since RcloneBrowser has "Shared" checkbox why not make for the "Trash" too right? So I don't have a dupe of every remote for the trash.

Before "Shared" checkbox I do actually have 3 remotes for each account, you know what I mean.

<img width="95" alt="04" src="https://user-images.githubusercontent.com/35872889/75236963-25bb7b00-57f1-11ea-9268-112de6e104c3.png">

**Comment by kapitainsky** [comment]
ok - so definitely doable. I don't expect to add this quickly though. All "google shared with me" code is very messy and would be good to clean it before adding even more complexity.
Also feel free to add this future yourself if you think it is urgent.

**Comment by thanamaha2002** [comment]
> ok - so definitely doable. I don't expect to add this quickly though. All "google shared with me" code is very messy and would be good to clean it before adding even more complexity.
> Also feel free to add this future yourself if you think it is urgent.

Thank you for looking into this. I not a programmer myself, and not urgently for the feature, I'll wait for your update. :)

PS. I update my reply: https://github.com/kapitainsky/RcloneBrowser/issues/82#issuecomment-590783306

It has some trick that would help in some situations like you accidentally delete files from complex directory structures and when you restore all files from trash by the website the directory structure will be destroyed. But if you use rclone to move files from the trash the directory structure will be preserved.

**Comment by kapitainsky** [comment]
Good that it is all working now too using additional "Google Thrash" remote. It is nice trick:)

**Comment by kapitainsky** [comment]
I have it working:) Let me know what OS you are on and I send you latest version for testing.
I am not releasing it yet as want to add few other things.

**Comment by thanamaha2002** [comment]
@kapitainsky Thank You! much appreciated. I using Windows 10.

**Comment by kapitainsky** [comment]
Here you are the latest beta:

https://1drv.ms/u/s!Aq335pidOrBV3-hD_QD1Whw9u0I_Iw

It includes Google drive fix and many others improvements. I am still working on adding more features so it will be few weeks before another release.

I would appreciate if you can give me some feedback on this new version. Always good to hear from power users.

**Comment by thanamaha2002** [comment]
Give me one day to test it. :)

**Comment by kapitainsky** [comment]
Take you time:) Great if you use it and if you notice something not working let me know in this thread.

Also any suggestions are also welcomed. Like this one with Google trash - I was not even aware that google support it.

**Comment by thanamaha2002** [comment]
After I testing so far this is my opinion.

1. I wish there is an option to use the old vertical list for the remote list. The current list is kinda messed if there is a lot of remotes with different name length. [Here the screenshot](https://user-images.githubusercontent.com/35872889/75991107-8bfa7900-5f28-11ea-8462-4290c06c9e88.png).

2. Stream feature not working with Trash. I check the command line it doesn't have **--drive-trashed-only** when using Stream feature. The same bug also found with Share with me too (**--drive-shared-with-me** is needed).

**Comment by kapitainsky** [comment]
>     1. I wish there is an option to use the old vertical list for the remote list. The current list is kinda messed if there is a lot of remotes with different name length. [Here the screenshot](https://user-images.githubusercontent.com/35872889/75991107-8bfa7900-5f28-11ea-8462-4290c06c9e88.png).

change in preferences "Remotes Icons Layout" to tiles - maybe it is solution?

>     2. **Stream** feature not working with **Trash**. I check the command line it doesn't have **--drive-trashed-only** when using **Stream** feature. The same bug also found with **Share with me** too (**--drive-shared-with-me** is needed).

I will check this one.

**Comment by kapitainsky** [comment]
Streaming is trivial fix - thanks for noticing. It will be fixed in the final version

**Comment by thanamaha2002** [comment]
Yes, please add "One column list" :)

**Comment by thanamaha2002** [comment]
I found another bug while changing between **Main**, **Shared with me** and **Trash**. Here how to replicate:

Open the drive and browse through some sub-directory that has files in it. Then change to **Trash** it will only refresh the root of the drive but files in the sub-directory still there even those files, not in the **Trash**.

But if you change to **Shared with me** then change to **Trash** this bug won't happen because it will clear all directory before refreshing the drive (It won't keep directory structure).

Solution: It needs to clear all directory then refresh it to another type of drive.

**Comment by thanamaha2002** [comment]
> Yet another question. Would would be most useful new feature you would like to see in this app?

I thinking about the **Dedupe** feature since you have a **Check** feature. Google Drive have a problem with duplicate files, you can have 2 files with the same name in the same directory or even the same directories with the same name in the same place.

It can happen by the user's intention or if you upload a lot of files rapidly using rclone and then you need to re-upload the same directory again but Google hasn't done the indexing file, rclone won't know the file was there when it checks then it will upload the same file again. This will result in a lot of duplicated files or directories.

Luckily, rclone has command call [**Dedupe**](https://rclone.org/commands/rclone_dedupe/), it will scan the duplicated files and directories then it'll automatically process it with the option we giving.

This is pretty easy you can make a new dialog like **Check** feature but with **Dedupe** option.

Here is an example of the **Dedupe** command line:

`".\rclone.exe" --config=".\rclone.conf" dedupe "TestRemote:test/test directory/" --dedupe-mode largest --checkers 20`

In the **Dedupe** you can make **ComboBox** that user can choose dedupe mode:

Skip - removes identical files then skips anything left. `--dedupe-mode skip`
First - removes identical files then keeps the first one. `--dedupe-mode first`
Newest - removes identical files then keeps the newest one. `--dedupe-mode newest`
Oldest - removes identical files then keeps the oldest one. `--dedupe-mode oldest`
Largest - removes identical files then keeps the largest one. `--dedupe-mode largest`
Rename - removes identical files then renames the rest to be different. `--dedupe-mode rename`

And **"Google Drive Use Trash"** **CheckBox** to decide if deleted files and directories will be sent to the trash or permanently remove by using this option. It only works on Google Drive that why the name is **"Google Drive Use Trash"** and should be checked by default. If the user unchecked this option it will add this to the command line:

`--drive-use-trash=false`

And it should have a **Dry Run** button too.
