### ISSUE TITLE
Need to click exit twice for application to actually exit

### ISSUE THREAD

**Issue by kayg04** [kapitainsky/RcloneBrowser#85]
For Rclone Browser to actually exit after enabling system tray, you need to do: `Right Click -> Quit` twice. For the first time, it closes the window and on the next, it kills the application. I think closing from the system tray should directly quit the app.

**Comment by kapitainsky** [comment]
I guess you set close to system tray in preferences?

**Comment by kayg04** [comment]
Yes.

**Comment by kapitainsky** [comment]
ok - I will check the flow here. might be buggy indeed

**Comment by kapitainsky** [comment]
it should be fixed now in kptsky_testing branch

**Comment by kayg04** [comment]
Yes, it works now. Thanks a lot!
