### ISSUE TITLE
Is Dark Mode really needed for Linux? - please share your view

### ISSUE THREAD

**Issue by kayg04** [kapitainsky/RcloneBrowser#86]
Is dark mode really needed on linux where you can apply a theme from a large variety to achieve the same effect?

**Comment by kapitainsky** [comment]
Do you think all distros support themes?

I don’t know Linux enough but if not needed  just maybe don’t use it?

**Comment by kayg04** [comment]
I don't think theming is distro specific at all. 

You could apply themes by using `qt5ct` and `kvantum` on any distro. 

https://wiki.archlinux.org/index.php/Qt#Qt5

**Comment by kapitainsky** [comment]
Ok. Thx. Something for me to read and think how to approach it.

I develop on mac and majority of users are on Windows. So Linux does not have greater visibility for my dev. 

Said that I definitely want to make sure that this app works on Linux - just having two other environments to care about sometimes leaves little time for Linux.

**Comment by kayg04** [comment]
I can just ignore the option, yes, obviously. But the option is redundant and might be extra work for you to keep as "theming" is something that can easily (and should) be done client-side.

**Comment by kayg04** [comment]
I think, for development, you could easily run Linux on a VM? Perhaps, Virtualbox or VMWare (I'm unaware if a OSS solution exists for MacOS) with [KDE Neon](https://neon.kde.org/download)?

**Comment by kapitainsky** [comment]
Yeap - agree. Will do some research on this.

**Comment by kapitainsky** [comment]
Yes it is easy - but time is limited:) so sometimes Linux suffers

**Comment by kayg04** [comment]
Yeah, I understand. I'm quite grateful as is that you're maintaining this. :)

If you're busy and need someone to test a few things on linux, I'd be happy to spin a vanilla KDE Neon VM up tomorrow.

**Comment by kapitainsky** [comment]
Definitely your comments today are super helpful.

I don’t do very structured development - when time permits I fix or add things, And when there is enough of them I release it.

If you think you could fix some issue that PR are always welcomed - this is not “my project” but open source approach.

**Comment by kapitainsky** [comment]
And just found this re themes... 

https://www.omgubuntu.co.uk/2019/05/open-letter-stop-gtk-theming-distros

**Comment by kapitainsky** [comment]
I would love more people to have say on this dark mode story - let;s see if anybody provides some thoughts

**Comment by kayg04** [comment]
Indeed. The server side decorations vs client side decorations debate has been going on for a while. My opinion on it is that theming should be entirely left to the client side with a fallback or a default that has been chosen by the developers. For example, Breeze for QT or Adwaita for GTK.

**Comment by kapitainsky** [comment]
In principle I agree but it would be ideal world. I spoke with few friends who use Linux as casual users and they turn dark mode from within RcloneBrowser. Yes they are aware that they can install some Qt customization apps but then results are so mixed for different apps that they prefer to stay with defaults. Linux gives its users with total freedom - it is paradise for tinkers. But more and more users just want to use it. I understand that you are power user and you would prefer to have all options open but I don’t think the same can be said about majority of users.

I was investigating linux themes approach and I like it but it has its limits. Also there are limits in terms how much time I can devote to Rclone Browser dev.

Trying to keep it working on Linux, macOS and Windows leads often to looking for lowest common denominators - I can’t afford making it perfect on every platform. Definitely it is doable to make it better and existing version is not perfect - but it never will be,

Still I will try to make it at least dark and light themes friendly.

**Comment by kayg04** [comment]
> I spoke with few friends who use Linux as casual users and they turn dark mode from within RcloneBrowser.

I see. I wasn't aware if people actually used it as I haven't come across a dark mode option in the qt apps I use with the exception of Telegram Desktop which has theming of its own. I can ignore that option as you said. No problem. 

> I was investigating linux themes approach and I like it but it has its limits. Also there are limits in terms how much time I can devote to Rclone Browser dev.

Understandable. I'm already grateful that you have put in a significant amount of work. 

> Still I will try to make it at least dark and light themes friendly.

Yeah, that'd be a neat and desirabe balance. Thank you!

**Comment by kapitainsky** [comment]
Given overwhelming feedback received I close it.
