### ISSUE TITLE
Add Dedupe feature to RcloneBrowser

### ISSUE THREAD

**Issue by thanamaha2002** [kapitainsky/RcloneBrowser#88]
[According to this comment](https://github.com/kapitainsky/RcloneBrowser/issues/82#issuecomment-595464318)

> Yet another question. Would would be most useful new feature you would like to see in this app?

I thinking about the **Dedupe** feature since you have a **Check** feature. Google Drive have a problem with duplicate files, you can have 2 files with the same name in the same directory or even the same directories with the same name in the same place.

It can happen by the user's intention or if you upload a lot of files rapidly using rclone and then you need to re-upload the same directory again but Google hasn't done the indexing file, rclone won't know the file was there when it checks then it will upload the same file again. This will result in a lot of duplicated files or directories.

Luckily, rclone has command call [**Dedupe**](https://rclone.org/commands/rclone_dedupe/), it will scan the duplicated files and directories then it'll automatically process it with the option we giving.

This is pretty easy you can make a new dialog like **Check** feature but with **Dedupe** option.

Here is an example of the **Dedupe** command line:

`".\rclone.exe" --config=".\rclone.conf" dedupe "TestRemote:test/test directory/" --dedupe-mode largest --checkers 20`

In the **Dedupe** you can make **ComboBox** that user can choose dedupe mode:

Skip - removes identical files then skips anything left. `--dedupe-mode skip`
First - removes identical files then keeps the first one. `--dedupe-mode first`
Newest - removes identical files then keeps the newest one. `--dedupe-mode newest`
Oldest - removes identical files then keeps the oldest one. `--dedupe-mode oldest`
Largest - removes identical files then keeps the largest one. `--dedupe-mode largest`
Rename - removes identical files then renames the rest to be different. `--dedupe-mode rename`

And **"Google Drive Use Trash"** **CheckBox** to decide if deleted files and directories will be sent to the trash or permanently remove by using this option. It only works on Google Drive that why the name is **"Google Drive Use Trash"** and should be checked by default. If the user unchecked this option it will add this to the command line:

`--drive-use-trash=false`

And it should have a **Dry Run** button too.

**Comment by kapitainsky** [comment]
Nice suggestion - doable.

Do you know if any other remotes but Google drive support it? I don't want to display not needed button.

**Comment by thanamaha2002** [comment]
I not sure about other remotes but in the official rclone website said: `Only useful with Google Drive which can have duplicate file names.` But didn't say about other remote that might support duplicate. Maybe some other service that we didn't know is support or some service that support maybe add to rclone in the future. As for now all we know is Google Drive. I think it's OK for now to show **Dedupe** feature for Google Drive only.

`Also am I thinking right that "Skip, First, Newest, Oldest, Largest and Rename" options are mutually exclusive?`

Sorry, but what did you mean by mutually exclusive?

**Comment by kapitainsky** [comment]
> `Also am I thinking right that "Skip, First, Newest, Oldest, Largest and Rename" options are mutually exclusive?`
> 
> Sorry, but what did you mean by mutually exclusive?

Than only one can be selected at the time. You can't have any two or more together.

**Comment by thanamaha2002** [comment]
Yes, you can only selected one.

**Comment by thanamaha2002** [comment]
@kapitainsky And I have another suggestion, for **Check** and **Dedupe** can it send to **Jobs** tab after it runs? Because it takes some time to run, so the user can do other things while running.

**Comment by kapitainsky** [comment]
these windows are not blocking main window - you can keep working when check is running. On Windows unfortunately they stay "on top" - but you can just move them outside of your main window.

**Comment by thanamaha2002** [comment]
@kapitainsky When you have done all the bugs fixing and features, you can send me to help you test it. :)

**Comment by kapitainsky** [comment]
another beta ready  - with google drive dedupe and added tasks queue processing.

https://1drv.ms/u/s!Aq335pidOrBV3-hEcyYkwUGHh1ua8Q

**Comment by kapitainsky** [comment]
Also remotes long list is back

**Comment by thanamaha2002** [comment]
[This bug still exist](https://github.com/kapitainsky/RcloneBrowser/issues/82#issuecomment-595365723)

**Comment by kapitainsky** [comment]
Yes. I doubt I will ever fix it. Some weird issue.

**Comment by kapitainsky** [comment]
And not really show stopper. You want to restore some folders from trash. You can do it. Nobody is using trash for daily stuff

**Comment by thanamaha2002** [comment]
It not like **Shared with me**? Because that no problem with **Shared with me**, maybe you can fix by using **Shared with me** method. I guess.

**Comment by kapitainsky** [comment]
Both use exactly the same method. 

It is something weird with how trash listing are returned by rclone. Even when I use your workaround to go to trash via shared with me it only looks good initially. Try then refresh all few times. Some files and folders are duplicating...

Yes. There is some issue here. But I consider it extremely low importance. It would be nice to fix it. But I don’t know how. 

What about deduped? Working as intended?

**Comment by thanamaha2002** [comment]
Dedupe work as intended. But the **Stream** is bug, it not load file even on the Main drive. It must be something wrong but nothing to do with `--drive-trashed-only` or `--drive-shared-with-me`

**Comment by kapitainsky** [comment]
Thank you very much. Another issue to fix.

**Comment by kapitainsky** [comment]
> [This bug still exist](https://github.com/kapitainsky/RcloneBrowser/issues/82#issuecomment-595365723)

I looked a bit closet at it and I am convince it is related to very weird way Google Drive trash works/rclone handles it.

It seems that trash always contains full directory structure from Main drive. Including folders never deleted before.

Easy way to test. Create new folder in "main" drive then use command line: 
`rclone lsd Google: --drive-trashed-only`

and you will see you new folder there. Even when Trash is fully purged it contains at least from rclone perspective full directory structure on "main" drive.

**Comment by kapitainsky** [comment]
if you think that it is wrong and fixing is needed you can bring it to rclone forum

**Comment by thanamaha2002** [comment]
I know about the directory structure and how rclone handle it but not the bug I mention, this is about the GUI. I'll show you step by step.

1. To demonstrate how it bug, I'll open the directory in the Main drive which have test.txt in it.

<img width="852" alt="01" src="https://user-images.githubusercontent.com/35872889/76316484-45809200-630d-11ea-8da3-20c05f308322.png">

2. Then I'll change to Trash, the test.txt still show even it not in the Trash.

<img width="851" alt="02" src="https://user-images.githubusercontent.com/35872889/76316503-4c0f0980-630d-11ea-93b8-1d1dd46c5c8f.png">

3. Then look when I open the Shared with me.

<img width="851" alt="03" src="https://user-images.githubusercontent.com/35872889/76316515-4fa29080-630d-11ea-9777-af0b449893e4.png">

4. Then I go to Trash again. And when I open TEST directory it refresh and don't show test.txt.

<img width="848" alt="04" src="https://user-images.githubusercontent.com/35872889/76316527-53ceae00-630d-11ea-9cbe-87a144287adc.png">

5. So, if you open Main then open Shared with me then open the Trash this won't happen.

What I think to fix this is to clear all directories before loading Trash (meaning you all directories should be collapse) before loading Trash or purge it then load Trash like when we open Shared with me first.

P.S. file that at the root don't have this bug because when we change to Trash it only refresh the root.

**Comment by thanamaha2002** [comment]
Imagine if user open lot of directories the change to Trash they need to refresh directory by directory, it's easier that they change to Shared with me first then go to Trash again. But average users will have a hard to figure it out and they will think this is weird UX design.

**Comment by kapitainsky** [comment]
I agree but for some reason directories tree model does not:)  The same code is used to show shared and trash - just rclone lsd/ls is run with different switch. And it produces results you see. What’s the reason I have no clue at the moment. I wonder now if there is the same issue with “shared” - when you would have the same folder name as in “main"

**Comment by thanamaha2002** [comment]
If the directories tree model does not support the purge, then it's OK. 😭

**Comment by kapitainsky** [comment]
all can be done - it is only software. But so far I can’t figure out how to fix this particular issue.

**Comment by kapitainsky** [comment]
I think I have found how to handle it. When I have next beta version I will send you for testing.

**Comment by kapitainsky** [comment]
both trash and shared were affected btw - condition was that if in new model there was folder with the same name (on the same directories level) as in previous one it was not refreshed. It was more apparent in trash as it keeps all folders tree copy.

**Comment by kapitainsky** [comment]
https://1drv.ms/u/s!Aq335pidOrBV3-hHS3vxvzgFhvm3-Q

Please test:)

**Comment by thanamaha2002** [comment]
**IT WORKS!!** 😁

But the stream still bug, you haven't fixed yet?

**Comment by kapitainsky** [comment]
It should be fixed. I tested. What exactly fails in your test? Trash or shared or main?

**Comment by kapitainsky** [comment]
I don’t have any shared content to test share part.

**Comment by thanamaha2002** [comment]
All of them (main, shared and trash). Before this [release](https://github.com/kapitainsky/RcloneBrowser/issues/88#issuecomment-596215654), the main still working.

**Comment by kapitainsky** [comment]
Ok. This is weird but definitely there is some issue. I tried Main and trash and could stream no issues. Maybe it is something windows specific. I will check

**Comment by kapitainsky** [comment]
I have added "copy rclone command" to stream and mount jobs

<img width="1121" alt="Screenshot 2020-03-11 at 07 59 26" src="https://user-images.githubusercontent.com/15635386/76395077-780ea700-636e-11ea-9d32-69562bbc94fa.png">


Here you can download updated beta here:

https://1drv.ms/u/s!Aq335pidOrBV3-hIiKjAaJxsjbPWCw

Hopefully it will help to troubleshoot it. I tested again and both streaming and mount work perfectly regardless which instance of Google Drive I am using.

**Comment by thanamaha2002** [comment]
I found the problem, it was my default rclone option: `--exclude *.DS_Store` 

So, before this release, the default rclone option was not used for the stream. I think the default rclone option shouldn't use with stream command because who knows how many options that will conflict with the stream. And for users who already use the default rclone option and update to this version will think it a bug because they didn't change any settings and it doesn't work.

Or maybe you can add another field in preference below `Stream command:` name `rclone stream option:`

**Comment by kapitainsky** [comment]
Cool. 

--exclude *.DS_Store is not good option for this default - it should be in default download or upload options - have to check if not there by default by mistake

This default is rather for options like --fast-list or  --no-check-certificate which make sense for any operation

**Comment by kapitainsky** [comment]
Cool. 

--exclude *.DS_Store is not good option for this default - it should be in default download or upload options - have to check if not there by default by mistake

This default is rather for options like --fast-list or  --no-check-certificate which make sense for any operation

**Comment by thanamaha2002** [comment]
I see, thank you for clarify this and implement this feature. :)

Then I think we can close this issue, the feature is completed.
