### ISSUE TITLE
Progress Info not Populated/Blank

### ISSUE THREAD

**Issue by Parampaa** [kapitainsky/RcloneBrowser#9]
While it's still working, but It's just annoy me that the progress info doesn't contain any info.
I'm using latest Rclone Browser from here and newest Rclone exe available at this time.

![image](https://user-images.githubusercontent.com/9270306/65563465-de943a00-df73-11e9-953d-0413ac868f8b.png)

**Comment by kapitainsky** [comment]
You did not set verbose output option for this job (it means that rclone runs in quiet mode and there is no data browser can use to display any stats)

<img width="700" alt="Screenshot 2019-09-25 at 05 16 45" src="https://user-images.githubusercontent.com/15635386/65569047-f8258980-df53-11e9-9dc0-9d262fea6daf.png">

In the next release (already in beta) I will remove this option from UI and set it to always on. There are no practical reasons as I see to run without it. It is very annoying  indeed when not set and there is no information about long lasting job.

**Comment by kapitainsky** [comment]
I have just released next version 1.5. You can download it from [here](https://github.com/kapitainsky/RcloneBrowser/releases/tag/1.5)
