### ISSUE TITLE
Quick Stream Improvement!!

### ISSUE THREAD

**Issue by thanamaha2002** [kapitainsky/RcloneBrowser#90]
After playing with the stream feature I have a new idea for Rclone Browser to improvement and this is a quick one.

I using the mpv player for stream file and it supports setting a window title via command line, for example:

<img width="400" alt="01" src="https://user-images.githubusercontent.com/35872889/76486109-03606900-6451-11ea-93d7-83a098ae1df8.png">

<img width="907" alt="02" src="https://user-images.githubusercontent.com/35872889/76486123-0c513a80-6451-11ea-8ca2-a744b7dc8168.png">

What if we implement a parameter which Rclone Browser will replace it with a file name, it would be nice! for example:

Stream command: `.\mpv.exe --title="%file_name%" -`

When Rclone Browser run the command it will replace %file_name% with a file name, so the window title of the player will be the filename too!

**Comment by kapitainsky** [comment]
are there any length restrictions on `--title` ? Because file names can be very looong.

**Comment by thanamaha2002** [comment]
On Windows, the maximum command-line length is 32767 characters. Which I think more than enough since when people upload their files from Windows, for example, the full path length limit is 255 characters. It's the NTFS limitation since Windows NT 3.1... I wish M$ change this non-sense limit.

**Comment by thanamaha2002** [comment]
I check the Mac OS it's limit around 1016 characters and the Linux is 255 to 4096 characters depending on the disk format.

**Comment by thanamaha2002** [comment]
I check the Mac OS the **full-path** length limit around 1016 characters and the Linux is 255 to 4096 characters depending on the disk format.

The maximum command-line length is a lot higher. So, in the very extremely rare case that they will have file name length more than the command line limit length.

**Comment by kapitainsky** [comment]
I think most filesystems only allow 255 as maximum file name length 
but question is  about mpv player `--title` parameter. Will it accept 255 character? Could you check?

**Comment by kapitainsky** [comment]
And note to myself:) for VLC

> 
"/Applications/VLC.app" --meta-title "window title" -

**Comment by thanamaha2002** [comment]
I manage to find the limit length of mpv `--title` by brute force because I can't find this information in the mpv's docs ...

The limit of mpv `--title` length is exactly 1,000 characters.

**Comment by thanamaha2002** [comment]
I tested with the prohibited characters `\, /, :, *, ?, <, >, |` on Windows, it also works but not with the `"` it not show this characters on the window title (read below).

And after testing it's safer to use command like this `.\mpv.exe - --title="test"` than this `.\mpv.exe --title="test" -` 

Because if we have `"` in the file name it will bug and mpv window won't show if the command is `.\mpv.exe --title="\/:*?<>|"" -`

But with this `.\mpv.exe - --title="\/:*?<>|""` it works, just not show `"` on the window title (see pictures below).

<img width="400" alt="01" src="https://user-images.githubusercontent.com/35872889/76502999-9dd3a300-6477-11ea-93d0-0d807886bc19.png">

<img width="907" alt="02" src="https://user-images.githubusercontent.com/35872889/76502996-9c09df80-6477-11ea-8acc-908c325c78ef.png">

So, for your VLC is `/Applications/VLC.app" - --meta-title "window title"`

**Comment by kapitainsky** [comment]
Oki - so we know how to do it. I will add $FileName variable and toolTip explanation for end users how to use it.

**Comment by thanamaha2002** [comment]
I want to test this if you have a free time to compile for me, thanks. :)

**Comment by kapitainsky** [comment]
This feature is not implemented yet. It will be for sure. I am working on other features atm. When I have it stable I will send you beta. Tests are always welcomed.

**Comment by kapitainsky** [comment]
you test https://github.com/kapitainsky/RcloneBrowser/issues/93#issue-583234487

file name substitution is $file_name

**Comment by thanamaha2002** [comment]
Then, I'll close this issue and I'll report on that one instead. Thank for your hard-work!

**Comment by kapitainsky** [comment]
command copy issue has been fixed. It will make into final release.
