### ISSUE TITLE
update notifications don't work

### ISSUE THREAD

**Issue by Spelvi** [kapitainsky/RcloneBrowser#91]
I am in rclone 1.50.2 and 1.51.0 is available and I have update notifications activated and it does not notify me at all.

http://prntscr.com/rfzv0w

**Comment by kapitainsky** [comment]
What exactly OS you are on? 
Also please note that Rclone Browser tries to check new versions availability only once per day on application start.

**Comment by Spelvi** [comment]
Windows 10 64bit, never notify me, not once a day.

**Comment by kapitainsky** [comment]
Very strange. Windows 10 64bits should be least problematic.

To make sure could you test one more time tomorrow? Any time after midnight start Rclone Browser - it check new versions only on start, so for example you run it 24/7 it will never notify - something I should improve in the future.

If still does not work we will investigate further.

**Comment by Spelvi** [comment]
Since I am updating to the latest version today, I commented on it just to make sure that you do not notify me of the updates.

**Comment by kapitainsky** [comment]
I just checked on my laptop - works no issues.

If you would like to help with testing run rclone browser with older version of rclone.

start “Registry Editor”


go to “HKEY_CURRENT_USER\Software\rclone-browser\rclone-browser\Settings”

and change date of lastRcloneUpdateCheck key - does not have to be valid date - just change it to whatever.

Then you can start Rclone Browser and you should be notified about new version / or not. Works for me 100% of time.

**Comment by Spelvi** [comment]
Perform the steps that you indicate and I confirm that it worked.

**Comment by kapitainsky** [comment]
Thank you for testing! 

As said earlier I will change the way it works now - once per day but only when application star - to more predictable “schedule".
