### ISSUE TITLE
Terrible blue color on dark macOS

### ISSUE THREAD

**Issue by glensc** [kapitainsky/RcloneBrowser#92]
![image](https://user-images.githubusercontent.com/199095/76699574-694e2a00-66b7-11ea-8e69-75b531681af4.png)

I can't see that blue from a normal viewing distance, I have to get to 10cm from screen to read out the "releases" word :)

**Comment by kapitainsky** [comment]
Agree:) but I do not control this colour. It is whoever's behind Qt framework aesthetics regarding links colour in dark mode.

I have limited time to work on RB so I try to avoid small customizations as much as possible (I also release it for other OS so any change is x3 work).

I will always be more than happy if somebody makes it better and shares PR.

**Comment by kapitainsky** [comment]
Not sure what version of macOS you are using but on Catalina it looks better:

<img width="496" alt="Screenshot 2020-03-15 at 10 34 32" src="https://user-images.githubusercontent.com/15635386/76699779-ba0a5680-66a8-11ea-91fb-c51b2aa7eafb.png">

**Comment by glensc** [comment]
I have macOS 10.15.3 (Catalina). I don't recall doing any customization other than enabling dark mode.

ps: I installed via brew cask

**Comment by glensc** [comment]
ps2: my screenshot was from rclone browser, not rclone version check

**Comment by kapitainsky** [comment]
Install version from my releases - I have no idea what brew guys are doing - maybe they used different Qt version?

You can quickly check link colours in Rclone Browser about dialog. You don’t have to wait until another version pop up:)

**Comment by kapitainsky** [comment]
these are the same dialogs - does not matter
about uses the same style

**Comment by kapitainsky** [comment]
And let me know if it still looks terrible with latest release.

**Comment by glensc** [comment]
cask uses your `.dmg` images:
- https://github.com/Homebrew/homebrew-cask/blob/5b19c4b47573a04c8d031b32e27d361f80964003/Casks/kapitainsky-rclone-browser.rb#L5

**Comment by glensc** [comment]
> This program uses Qt version 5.13.2.

**Comment by kapitainsky** [comment]
Because it is old version. Brew channel is not maintained by myself - I have no idea how often they update it - if at all

The latest version or Rclone Browser uses Qt 5.14.1 - and it seems they fixed the “ugly blue”:)

Remove your brew one and install directly from here:

https://github.com/kapitainsky/RcloneBrowser/releases/latest <https://github.com/kapitainsky/RcloneBrowser/releases/latest>

**Comment by glensc** [comment]
Submitted PR to update to new version:
- https://github.com/Homebrew/homebrew-cask/pull/78716

**Comment by glensc** [comment]
Colors better with 1.8.0, indeed it was old Qt problem:

![image](https://user-images.githubusercontent.com/199095/76707752-a7207200-66fa-11ea-8022-248ba7e3ad60.png)

**Comment by kapitainsky** [comment]
Good we found what the issue was:)
