### ISSUE TITLE
Please add Rclone Browser to Chocolatey

### ISSUE THREAD

**Issue by xianx** [kapitainsky/RcloneBrowser#95]
Hello,

Thank you very much for this nice project. I was using mmozeiko/RcloneBrowser but the developer archived the project. I have just recently come to your fork. Many thanks to you as you have done a lots of improvement after the fork.

I am requesting you to add Rclone Browser to Chocolatey package. There are many Chocolatey user out there. Also adding to Chocolatey package gives user a hassel free update when ever new version is available.

There is also a Chocolatey package of old version https://chocolatey.org/packages/rclonebrowser

Will you please contact to the maintainer https://chocolatey.org/packages/rclonebrowser/ContactOwners and take over the project?

The maintainer also willing to handover the package according his last comment https://techtun.es/pqr3iQ

If the maintainer is not reachable or not possible to take over the package will you please add as a separate Chocolatey package with name like rclonebrowserfork or something like that which ever you prefer?

Also please keep in mind that please add Chocolatey package with auto update facility. Means, whenever a new release will be on github Chocolatey package will be auto upadte and new version will be available to chocolate user. 

I am not a developer just a user. So I am not expert on how to do this. I am suggesting to add rclonebrowser as Chocolatey package from a user perspective. As many chocolate package became outdated for not adding auto update facility of Chocolatey package.

Thanks in advance.

**Comment by kapitainsky** [comment]
Thank you for your nice comments but I don't want to get involved in supporting various delivery channels. There is enough work involved in keeping this tool running on all operating systems:) I provide everything required to run RB in this repo. If somebody is interested to push it to other distribution channels I would be only happy. A lot of people using other OS systems do it e.g.:

https://repology.org/project/rclone-browser/packages

I am not involved in it at all and as you can see it is slowly spreading.

With my version you are always notified when new version is available - you wont miss it.

BTW. If you are here I suggest you try the coming release:

https://1drv.ms/u/s!Aq335pidOrBV4II4JUmv10vuJYSXTw

It is still work in progress but I am looking for feedback.

**Comment by kapitainsky** [comment]
I also notice on chocolatey - https://chocolatey.org/packages/rclonebrowser - this: 

"It does look like there's an installer now instead of just a ZIP installer so there's a little more work than just subbing out the binaries. If there's interest in taking this over, please let me know. Thanks!"

There is installer now provided - so maybe it is easier than you think to add it? Why don't you try yourself? It does not require developing anything.

**Comment by kapitainsky** [comment]
another note - on chocolatey it had about 2000 downloads vs. 50000 directly from git. Seems like very niche coverage chocolatey has. Up to you:) I suggest you just install version directly from here (it will notify you when there is next version). You can also put comment to chocolatey directing people here - so they don't use really old and only half working version.
