### ISSUE TITLE
Critical Bug: RB should use Arabic numeral only.

### ISSUE THREAD

**Issue by thanamaha2002** [kapitainsky/RcloneBrowser#96]
My friend just installs a new Windows and this reminds me of the most critical bug of RB since mmozeiko has created it.

The problem is the RB use numeral from the system if you use Thai like my friend for example. You will get a result like a picture below.

<img width="821" alt="01" src="https://user-images.githubusercontent.com/35872889/77217820-e534f000-6b57-11ea-851f-cff654cbd08c.png">

And when RB passes the number to rclone it will bug because rclone supports only an Arabic numeral.

<img width="914" alt="02" src="https://user-images.githubusercontent.com/35872889/77217838-20cfba00-6b58-11ea-800d-0151d68d8f95.png">

My other friend that is a programmer (C#) also face the same problem but he fixes it programmatically and doesn't depend on system configuration. (His software not RB) So, I think RB can also fix to use only an Arabic numeral programmatically too.

The normal users will confuse and don't know how to fix this issue themself, that why when my friend installs a new Windows and he asks me why RB doesn't work and it's the same issue every time. I have to remote and change the numeral format for him but some users may really need to use their numeral system if they work on the document or something.

**Comment by kapitainsky** [comment]
This is very interesting. Even RB is only provided in english I would like to make sure that it works in any environment - including different locale setups.

I might have to test some idea - I will send you another beta later. rclone itself accepts only numerals (for options) in english so RB should reflect it.

**Comment by kapitainsky** [comment]
Problem is that probably very few languages nowadays don't use "arabic numerals" issue with particular software is easy overlooked.

**Comment by thanamaha2002** [comment]
In Windows it connected to date & time format of the system, I need to change that to en-GB to fix this. So, I think you should search for `Override date time format in Qt`

**Comment by kapitainsky** [comment]
I don’t see why user should not use their local language formats where applicable.

Here it is specific case - rclone itself understands only arabic numerals for parameters’ values.  Qt interface follows system locale settings. Problem is that SpinBoxes used to input for example checkers value return literal text - not number.

And as Thai might be the only language using special numerals we have an issue:)

I will think how to fix it - challenge is I don’t have Thai Windows so will ask you to test.

**Comment by thanamaha2002** [comment]
Of course, I'll help you test. :)

You're right. Maybe we just need to convert the numeral format in the background to create rclone command line and nothing to do with how the numeral show to its users. Or maybe it because RB take a string of the NumericUpDown box, it should take the value instead of a string, right?

**Comment by kapitainsky** [comment]
I am looking for solution to display these SpinBoxes using always arabic numerals. Otherwise it is misleading - as Bandwith, MinimumSize field etc. also require arabic numerals. When user sees SpinBoxes with thai numerals then naturally will use them in other settings as well.

It might be not perfect solution but I don't have time to fight localization issues. It is big and complex issue and like in your case it affects only very tiny amount of users. But we will try to find some way

**Comment by kapitainsky** [comment]
can you try this?

https://1drv.ms/u/s!Aq335pidOrBV4II8n-FqU_pNBC8V1A

**Comment by thanamaha2002** [comment]
It works! Now it only show Arabic numeral and it can run rclone no problem.

**Comment by kapitainsky** [comment]
one more test:) hold on

**Comment by kapitainsky** [comment]
Can  you try this?

https://1drv.ms/u/s!Aq335pidOrBV4II9l8NW3_hoo9isqg

When I know results of this I will feel confident that I can fix it.

**Comment by thanamaha2002** [comment]
The latest release also works, no problem. I didn't see the difference, what results do you expect?

**Comment by kapitainsky** [comment]
Great! Thx for reporting and testing.

In second test I wanted to check what local settings are  detected when th_TH is set on system level.

Next release will now always work for people who use thai system settings. Well done to us.

**Comment by thanamaha2002** [comment]
You did all the hard works! Well done to you sir! I also work from home, my gov. just declared a quarantine for 22 days, you also take care and be healthy.
