### ISSUE TITLE
Wishlist: Automated tasks!

### ISSUE THREAD

**Issue by AplhaSlayer1964** [kapitainsky/RcloneBrowser#99]
It would be awsome If we could set the tasks to be automated! 
Some examples:
Run task every X hours
Run task at X time of day
Also thank you for making this GUI for rclone it is amazing!

**Comment by kapitainsky** [comment]
it will be all included in the next release I am working on at the moment,

**Comment by AplhaSlayer1964** [comment]
That's awesome to hear! I can't wait!
